-- ============================================================================
-- 台鐵職工福利平台 — SYS 系統基礎模組
-- 模組：01_sys.sql
-- 說明：系統參數、字典、編號規則、排程任務、事件發件箱、資料導入與外部整合
-- 依賴：00_database.sql
-- ============================================================================

-- 前置檢查：確保目標資料庫存在
-- schema via search_path

-- ============================================================================
-- 1. 系統參數與字典
-- ============================================================================

-- SYS-01: 系統參數
CREATE TABLE IF NOT EXISTS sys_parameter (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    param_key       VARCHAR(100)    NOT NULL,
    param_value     TEXT            NOT NULL,
    value_type      VARCHAR(30)     NOT NULL DEFAULT 'string',
    scope_type      VARCHAR(30)     NOT NULL DEFAULT 'global',
    scope_id        BIGINT DEFAULT NULL,
    description     VARCHAR(500)    DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (param_key)
);

-- SYS-02: 系統參數變更歷史
CREATE TABLE IF NOT EXISTS sys_parameter_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parameter_id    BIGINT NOT NULL,
    param_key       VARCHAR(100)    NOT NULL,
    old_value       TEXT            DEFAULT NULL,
    new_value       TEXT            NOT NULL,
    changed_by      BIGINT DEFAULT NULL,
    change_reason   VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_parameter_id (parameter_id),
    INDEX idx_created_at (created_at)
);

-- SYS-03: 字典分類
CREATE TABLE IF NOT EXISTS sys_dictionary (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dict_code       VARCHAR(50)     NOT NULL,
    dict_name       VARCHAR(100)    NOT NULL,
    description     VARCHAR(500)    DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (dict_code)
);

-- SYS-04: 字典項目
CREATE TABLE IF NOT EXISTS sys_dictionary_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dict_id         BIGINT NOT NULL,
    item_code       VARCHAR(50)     NOT NULL,
    item_name       VARCHAR(100)    NOT NULL,
    sort_order      INT             NOT NULL DEFAULT 0,
    parent_item_id  BIGINT DEFAULT NULL,
    extra_json      JSONB            DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (dict_id, item_code),
    INDEX idx_parent_item (parent_item_id),
    CONSTRAINT fk_dict_item_dict FOREIGN KEY (dict_id) REFERENCES sys_dictionary(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dict_item_parent FOREIGN KEY (parent_item_id) REFERENCES sys_dictionary_item(id) ON DELETE SET NULL
);

-- ============================================================================
-- 2. 編號規則與流水
-- ============================================================================

-- SYS-05: 編號規則定義
CREATE TABLE IF NOT EXISTS sys_number_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rule_code       VARCHAR(50)     NOT NULL,
    rule_name       VARCHAR(100)    NOT NULL,
    format_pattern  VARCHAR(200)    NOT NULL,
    prefix          VARCHAR(20)     DEFAULT NULL,
    seq_min         INT             NOT NULL DEFAULT 1,
    seq_max         INT             NOT NULL DEFAULT 999999,
    seq_padding     INT             NOT NULL DEFAULT 6,
    reset_frequency VARCHAR(30)     NOT NULL DEFAULT 'never',
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (rule_code)
);

-- SYS-06: 編號流水狀態（併發安全）
CREATE TABLE IF NOT EXISTS sys_number_sequence (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rule_id         BIGINT NOT NULL,
    period_key      VARCHAR(30)     NOT NULL,
    current_seq     INT             NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (rule_id, period_key),
    CONSTRAINT fk_seq_rule FOREIGN KEY (rule_id) REFERENCES sys_number_rule(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 3. 排程任務
-- ============================================================================

-- SYS-07: 排程任務定義
CREATE TABLE IF NOT EXISTS sys_job_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_code        VARCHAR(50)     NOT NULL,
    job_name        VARCHAR(100)    NOT NULL,
    job_type        VARCHAR(30)     NOT NULL,
    cron_expression VARCHAR(100)    DEFAULT NULL,
    max_retries     INT             NOT NULL DEFAULT 3,
    timeout_seconds INT             NOT NULL DEFAULT 300,
    config_json     JSONB            DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (job_code)
);

-- SYS-08: 任務執行記錄
CREATE TABLE IF NOT EXISTS sys_job_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id          BIGINT NOT NULL,
    run_status      VARCHAR(30)     NOT NULL,
    started_at      TIMESTAMP(6)     NOT NULL,
    finished_at     TIMESTAMP(6)     DEFAULT NULL,
    result_summary  VARCHAR(500)    DEFAULT NULL,
    error_message   TEXT            DEFAULT NULL,
    retry_count     INT             NOT NULL DEFAULT 0,
    triggered_by    VARCHAR(50)     NOT NULL DEFAULT 'scheduler',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_job_id (job_id),
    INDEX idx_run_status (run_status),
    INDEX idx_started_at (started_at),
    CONSTRAINT fk_job_run_definition FOREIGN KEY (job_id) REFERENCES sys_job_definition(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 4. 跨模組事件發件箱
-- ============================================================================

-- SYS-09: 事件發件箱
CREATE TABLE IF NOT EXISTS sys_outbox_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id        VARCHAR(64)     NOT NULL,
    aggregate_type  VARCHAR(50)     NOT NULL,
    aggregate_id    BIGINT NOT NULL,
    event_type      VARCHAR(100)    NOT NULL,
    payload_json    JSONB            NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMP(6)     DEFAULT NULL,
    retry_count     INT             NOT NULL DEFAULT 0,
    last_error      TEXT            DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (event_id),
    INDEX idx_aggregate (aggregate_type, aggregate_id),
    INDEX idx_publish_status (published_at, retry_count),
    INDEX idx_created_at (created_at)
);

-- SYS-10: 事件消費冪等記錄
CREATE TABLE IF NOT EXISTS sys_event_consume_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    consumer_code   VARCHAR(50)     NOT NULL,
    event_id        VARCHAR(64)     NOT NULL,
    consume_status  VARCHAR(30)     NOT NULL,
    error_message   TEXT            DEFAULT NULL,
    consumed_at     TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (consumer_code, event_id),
    INDEX idx_consumed_at (consumed_at)
);

-- ============================================================================
-- 5. 資料導入
-- ============================================================================

-- SYS-11: 導入任務
CREATE TABLE IF NOT EXISTS sys_import_job (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    import_type     VARCHAR(50)     NOT NULL,
    file_key        VARCHAR(128)    DEFAULT NULL,
    checksum        VARCHAR(128)    DEFAULT NULL,
    total_rows      INT             NOT NULL DEFAULT 0,
    success_rows    INT             NOT NULL DEFAULT 0,
    failed_rows     INT             NOT NULL DEFAULT 0,
    import_status   VARCHAR(30)     NOT NULL DEFAULT 'pending',
    started_at      TIMESTAMP(6)     DEFAULT NULL,
    finished_at     TIMESTAMP(6)     DEFAULT NULL,
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_import_type (import_type),
    INDEX idx_import_status (import_status),
    INDEX idx_created_at (created_at)
);

-- SYS-12: 導入行錯誤
CREATE TABLE IF NOT EXISTS sys_import_row_error (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    import_job_id   BIGINT NOT NULL,
    row_index       INT             NOT NULL,
    raw_value_json  JSONB            NOT NULL,
    cleaned_value_json JSONB         DEFAULT NULL,
    error_message   TEXT            NOT NULL,
    is_resolved     BOOLEAN      NOT NULL DEFAULT 0,
    resolved_by     BIGINT DEFAULT NULL,
    resolved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_import_job_id (import_job_id),
    INDEX idx_is_resolved (is_resolved),
    CONSTRAINT fk_import_error_job FOREIGN KEY (import_job_id) REFERENCES sys_import_job(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 6. 外部整合
-- ============================================================================

-- SYS-13: 外部介接端點設定
CREATE TABLE IF NOT EXISTS sys_integration_endpoint (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint_code   VARCHAR(50)     NOT NULL,
    endpoint_name   VARCHAR(100)    NOT NULL,
    provider_type   VARCHAR(50)     NOT NULL,
    base_url        VARCHAR(500)    DEFAULT NULL,
    auth_type       VARCHAR(30)     NOT NULL DEFAULT 'none',
    secret_ref      VARCHAR(200)    DEFAULT NULL,
    timeout_seconds INT             NOT NULL DEFAULT 30,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (endpoint_code)
);

-- SYS-14: 外部同步執行記錄
CREATE TABLE IF NOT EXISTS sys_integration_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint_id     BIGINT NOT NULL,
    run_type        VARCHAR(50)     NOT NULL,
    run_status      VARCHAR(30)     NOT NULL,
    total_count     INT             NOT NULL DEFAULT 0,
    success_count   INT             NOT NULL DEFAULT 0,
    failed_count    INT             NOT NULL DEFAULT 0,
    started_at      TIMESTAMP(6)     NOT NULL,
    finished_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_endpoint_id (endpoint_id),
    INDEX idx_run_status (run_status),
    INDEX idx_started_at (started_at),
    CONSTRAINT fk_integration_run_endpoint FOREIGN KEY (endpoint_id) REFERENCES sys_integration_endpoint(id) ON DELETE RESTRICT
);

-- SYS-15: 外部同步失敗記錄
CREATE TABLE IF NOT EXISTS sys_integration_error (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    integration_run_id BIGINT NOT NULL,
    object_type     VARCHAR(50)     DEFAULT NULL,
    object_id       VARCHAR(100)    DEFAULT NULL,
    error_type      VARCHAR(50)     NOT NULL,
    error_message   TEXT            NOT NULL,
    raw_response    TEXT            DEFAULT NULL,
    is_retryable    BOOLEAN      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_integration_run_id (integration_run_id),
    CONSTRAINT fk_integration_error_run FOREIGN KEY (integration_run_id) REFERENCES sys_integration_run(id) ON DELETE RESTRICT
);
