-- ============================================================================
-- 台鐵職工福利平台 — FILE 檔案資源模組
-- 模組：02_file.sql
-- 說明：物件儲存元資料、分段上傳、惡意掃描、內容檢查、存取記錄與保存策略
-- 依賴：01_sys.sql
-- 設計原則：二進位檔案不存入 MySQL、無多態 target_type/target_id 業務關聯
-- ============================================================================

-- schema via search_path

-- FILE-01: 檔案物件
CREATE TABLE IF NOT EXISTS file_object (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    storage_key         VARCHAR(255)    NOT NULL,
    original_name       VARCHAR(255)    NOT NULL,
    mime_type           VARCHAR(100)    DEFAULT NULL,
    file_size_bytes     BIGINT NOT NULL DEFAULT 0,
    page_count          INT             DEFAULT NULL,
    image_width         INT             DEFAULT NULL,
    image_height        INT             DEFAULT NULL,
    checksum_sha256     VARCHAR(64)     DEFAULT NULL,
    storage_provider    VARCHAR(50)     NOT NULL DEFAULT 'local',
    encryption_status   VARCHAR(30)     NOT NULL DEFAULT 'none',
    sensitivity_level   VARCHAR(30)     NOT NULL DEFAULT 'normal',
    access_level        VARCHAR(30)     NOT NULL DEFAULT 'internal',
    file_status         VARCHAR(30)     NOT NULL DEFAULT 'active',
    uploaded_by         BIGINT DEFAULT NULL,
    module_code         VARCHAR(30)     DEFAULT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (storage_key),
    INDEX idx_checksum (checksum_sha256),
    INDEX idx_file_status (file_status),
    INDEX idx_sensitivity (sensitivity_level),
    INDEX idx_uploaded_by (uploaded_by),
    INDEX idx_module_code (module_code)
);

-- FILE-02: 分段上傳工作階段
CREATE TABLE IF NOT EXISTS file_upload_session (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_key     VARCHAR(64)     NOT NULL,
    original_name   VARCHAR(255)    NOT NULL,
    mime_type       VARCHAR(100)    DEFAULT NULL,
    total_size      BIGINT NOT NULL DEFAULT 0,
    chunk_size      INT             NOT NULL DEFAULT 5242880,
    total_chunks    INT             NOT NULL DEFAULT 0,
    received_chunks INT             NOT NULL DEFAULT 0,
    session_status  VARCHAR(30)     NOT NULL DEFAULT 'initiated',
    expires_at      TIMESTAMP(6)     NOT NULL,
    uploaded_by     BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (session_key),
    INDEX idx_session_status (session_status),
    INDEX idx_expires_at (expires_at)
);

-- FILE-03: 惡意軟體掃描結果
CREATE TABLE IF NOT EXISTS file_malware_scan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_id         BIGINT NOT NULL,
    scanner_name    VARCHAR(50)     NOT NULL,
    scan_status     VARCHAR(30)     NOT NULL,
    threat_name     VARCHAR(200)    DEFAULT NULL,
    scan_details    TEXT            DEFAULT NULL,
    scanned_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_file_id (file_id),
    INDEX idx_scan_status (scan_status),
    CONSTRAINT fk_malware_scan_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- FILE-04: 檔案內容檢查
CREATE TABLE IF NOT EXISTS file_content_inspection (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_id         BIGINT NOT NULL,
    inspection_type VARCHAR(50)     NOT NULL,
    result_status   VARCHAR(30)     NOT NULL,
    result_value    VARCHAR(255)    DEFAULT NULL,
    inspection_json JSONB            DEFAULT NULL,
    inspected_at    TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_file_id (file_id),
    CONSTRAINT fk_content_inspection_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- FILE-05: 檔案存取記錄（僅可追加）
CREATE TABLE IF NOT EXISTS file_access_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_id         BIGINT NOT NULL,
    access_type     VARCHAR(30)     NOT NULL,
    accessed_by     BIGINT DEFAULT NULL,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    request_trace   VARCHAR(64)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_file_id (file_id),
    INDEX idx_accessed_by (accessed_by),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_access_log_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- FILE-06: 檔案保存策略
CREATE TABLE IF NOT EXISTS file_retention_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_code     VARCHAR(50)     NOT NULL,
    policy_name     VARCHAR(100)    NOT NULL,
    retention_days  INT             NOT NULL,
    archive_days    INT             DEFAULT NULL,
    destroy_after   BOOLEAN      NOT NULL DEFAULT 0,
    applies_to      VARCHAR(50)     NOT NULL DEFAULT '*',
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (policy_code)
);
