-- ============================================================================
-- 台鐵職工福利平台 — ORG 組織架構模組
-- 模組：03_org.sql
-- 說明：組織單位、閉包表、歷史、職位、任職、任職業務範圍、組織變更與導入
-- 依賴：01_sys.sql
-- ============================================================================

-- schema via search_path

-- ORG-01: 組織單位主檔
CREATE TABLE IF NOT EXISTS org_unit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    unit_code       VARCHAR(30)     NOT NULL,
    unit_name       VARCHAR(100)    NOT NULL,
    unit_type       VARCHAR(30)     NOT NULL,
    parent_id       BIGINT DEFAULT NULL,
    manager_position_id BIGINT DEFAULT NULL,
    contact_phone   VARCHAR(30)     DEFAULT NULL,
    contact_address VARCHAR(200)    DEFAULT NULL,
    sort_order      INT             NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (unit_code),
    INDEX idx_parent_id (parent_id),
    INDEX idx_unit_type (unit_type),
    INDEX idx_is_active (is_active, expiration_date),
    CONSTRAINT fk_org_unit_parent FOREIGN KEY (parent_id) REFERENCES org_unit(id) ON DELETE RESTRICT
);

-- ORG-02: 組織閉包表（祖先-後代關係）
CREATE TABLE IF NOT EXISTS org_unit_closure (
    ancestor_id     BIGINT NOT NULL,
    descendant_id   BIGINT NOT NULL,
    depth           INT             NOT NULL,
    PRIMARY KEY (ancestor_id, descendant_id),
    INDEX idx_descendant (descendant_id),
    INDEX idx_depth (depth),
    CONSTRAINT fk_closure_ancestor FOREIGN KEY (ancestor_id) REFERENCES org_unit(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closure_descendant FOREIGN KEY (descendant_id) REFERENCES org_unit(id) ON DELETE RESTRICT
);

-- ORG-03: 組織單位歷史
CREATE TABLE IF NOT EXISTS org_unit_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    unit_id         BIGINT NOT NULL,
    unit_code       VARCHAR(30)     NOT NULL,
    unit_name       VARCHAR(100)    NOT NULL,
    parent_id       BIGINT DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL,
    effective_date  DATE            NOT NULL,
    change_type     VARCHAR(30)     NOT NULL,
    changed_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_unit_id (unit_id),
    INDEX idx_unit_code (unit_code),
    INDEX idx_effective_date (effective_date),
    CONSTRAINT fk_unit_history_unit FOREIGN KEY (unit_id) REFERENCES org_unit(id) ON DELETE RESTRICT
);

-- ORG-04: 職位
CREATE TABLE IF NOT EXISTS org_position (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    position_code   VARCHAR(30)     NOT NULL,
    position_name   VARCHAR(100)    NOT NULL,
    org_unit_id     BIGINT DEFAULT NULL,
    sort_order      INT             NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (position_code),
    INDEX idx_org_unit_id (org_unit_id),
    CONSTRAINT fk_position_org FOREIGN KEY (org_unit_id) REFERENCES org_unit(id) ON DELETE SET NULL
);

-- ORG-05: 組織變更申請
CREATE TABLE IF NOT EXISTS org_change_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_no      VARCHAR(50)     NOT NULL,
    change_type     VARCHAR(30)     NOT NULL,
    target_unit_id  BIGINT DEFAULT NULL,
    proposed_name   VARCHAR(100)    DEFAULT NULL,
    reason          TEXT            NOT NULL,
    request_status  VARCHAR(30)     NOT NULL DEFAULT 'draft',
    requested_by    BIGINT NOT NULL,
    approved_by     BIGINT DEFAULT NULL,
    approved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (request_no),
    INDEX idx_target_unit (target_unit_id),
    INDEX idx_request_status (request_status)
);

-- ORG-06: 組織變更影響分析
CREATE TABLE IF NOT EXISTS org_change_impact (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    change_request_id BIGINT NOT NULL,
    impact_type     VARCHAR(30)     NOT NULL,
    affected_object_type VARCHAR(50) NOT NULL,
    affected_object_id  BIGINT NOT NULL,
    impact_description TEXT        NOT NULL,
    is_resolved     BOOLEAN      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_change_request_id (change_request_id),
    CONSTRAINT fk_impact_change_request FOREIGN KEY (change_request_id) REFERENCES org_change_request(id) ON DELETE RESTRICT
);

-- ORG-07: 組織變更與工作流關聯（不含 wf_instance 外鍵——由 WF 模組安裝後保證引用完整性）
CREATE TABLE IF NOT EXISTS org_change_approval_link (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    change_request_id BIGINT NOT NULL,
    wf_instance_id  BIGINT NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (change_request_id, wf_instance_id),
    INDEX idx_wf_instance (wf_instance_id),
    CONSTRAINT fk_approval_link_change FOREIGN KEY (change_request_id) REFERENCES org_change_request(id) ON DELETE RESTRICT
);

-- ORG-08: 組織資料導入批次
CREATE TABLE IF NOT EXISTS org_import_batch (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    import_job_id   BIGINT DEFAULT NULL,
    total_units     INT             NOT NULL DEFAULT 0,
    created_units   INT             NOT NULL DEFAULT 0,
    updated_units   INT             NOT NULL DEFAULT 0,
    import_status   VARCHAR(30)     NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_import_job_id (import_job_id)
);
