-- ============================================================================
-- 台鐵職工福利平台 — EMP 職工與眷屬模組
-- 模組：04_emp.sql
-- 說明：職工主檔、聯絡資料、地址、任職歷史、福利社歸屬、眷屬、教育、扣繳、資格快照、
--       任職記錄與業務範圍（因 FK 依賴 emp_employee，從 ORG 模組移入）
-- 依賴：01_sys.sql、03_org.sql
-- ============================================================================

-- schema via search_path

-- EMP-01: 職工主檔
CREATE TABLE IF NOT EXISTS emp_employee (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_no             VARCHAR(20)     NOT NULL,
    id_card_hash            VARCHAR(64)     DEFAULT NULL,
    id_card_encrypted       TEXT            DEFAULT NULL,
    name                    VARCHAR(100)    NOT NULL,
    name_romanized          VARCHAR(100)    DEFAULT NULL,
    gender                  VARCHAR(10)     DEFAULT NULL,
    birth_date              DATE            DEFAULT NULL,
    employment_status       VARCHAR(30)     NOT NULL DEFAULT 'active',
    hire_date               DATE            DEFAULT NULL,
    resignation_date        DATE            DEFAULT NULL,
    primary_org_unit_id     BIGINT DEFAULT NULL,
    primary_welfare_shop_id BIGINT DEFAULT NULL,
    bank_account_hash       VARCHAR(64)     DEFAULT NULL,
    bank_account_encrypted  TEXT            DEFAULT NULL,
    is_active               BOOLEAN      NOT NULL DEFAULT 1,
    created_at              TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (employee_no),
    INDEX idx_id_card_hash (id_card_hash),
    INDEX idx_bank_account_hash (bank_account_hash),
    INDEX idx_employment_status (employment_status),
    KEY idx_primary_org (primary_org_unit_id),
    KEY idx_primary_welfare (primary_welfare_shop_id),
    INDEX idx_name (name),
    CONSTRAINT fk_employee_org FOREIGN KEY (primary_org_unit_id) REFERENCES org_unit(id) ON DELETE SET NULL,
    CONSTRAINT fk_employee_welfare FOREIGN KEY (primary_welfare_shop_id) REFERENCES org_unit(id) ON DELETE SET NULL
);

-- EMP-02: 職工聯絡資料
CREATE TABLE IF NOT EXISTS emp_contact (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    contact_type    VARCHAR(30)     NOT NULL,
    contact_value   VARCHAR(200)    NOT NULL,
    is_primary      BOOLEAN      NOT NULL DEFAULT 0,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_contact_type (contact_type),
    CONSTRAINT fk_contact_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT
);

-- EMP-03: 職工通訊地址
CREATE TABLE IF NOT EXISTS emp_address (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    address_type    VARCHAR(30)     NOT NULL DEFAULT 'residence',
    address_line1   VARCHAR(200)    NOT NULL,
    address_line2   VARCHAR(200)    DEFAULT NULL,
    city            VARCHAR(100)    DEFAULT NULL,
    district        VARCHAR(100)    DEFAULT NULL,
    postal_code     VARCHAR(10)     DEFAULT NULL,
    is_primary      BOOLEAN      NOT NULL DEFAULT 0,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_address_type (address_type),
    CONSTRAINT fk_address_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT
);

-- EMP-04: 任職歷史
CREATE TABLE IF NOT EXISTS emp_employment_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    org_unit_id     BIGINT NOT NULL,
    job_title       VARCHAR(100)    DEFAULT NULL,
    position_id     BIGINT DEFAULT NULL,
    employment_type VARCHAR(30)     DEFAULT NULL,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    change_reason   VARCHAR(200)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_org_unit_id (org_unit_id),
    INDEX idx_effective_date (effective_date),
    CONSTRAINT fk_emp_history_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT,
    CONSTRAINT fk_emp_history_org FOREIGN KEY (org_unit_id) REFERENCES org_unit(id) ON DELETE RESTRICT
);

-- EMP-05: 福利社歸屬歷史
CREATE TABLE IF NOT EXISTS emp_welfare_branch_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    welfare_shop_id BIGINT NOT NULL,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    change_reason   VARCHAR(200)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_welfare_shop_id (welfare_shop_id),
    INDEX idx_effective_date (effective_date),
    CONSTRAINT fk_welfare_hist_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT,
    CONSTRAINT fk_welfare_hist_shop FOREIGN KEY (welfare_shop_id) REFERENCES org_unit(id) ON DELETE RESTRICT
);

-- EMP-06: 眷屬主檔
CREATE TABLE IF NOT EXISTS emp_dependent (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    name            VARCHAR(100)    NOT NULL,
    relationship    VARCHAR(30)     NOT NULL,
    id_card_hash    VARCHAR(64)     DEFAULT NULL,
    id_card_encrypted TEXT         DEFAULT NULL,
    birth_date      DATE            DEFAULT NULL,
    gender          VARCHAR(10)     DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_relationship (relationship),
    CONSTRAINT fk_dependent_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT
);

-- EMP-07: 子女教育資料
CREATE TABLE IF NOT EXISTS emp_dependent_education (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dependent_id    BIGINT NOT NULL,
    school_name     VARCHAR(200)    NOT NULL,
    education_level VARCHAR(30)     NOT NULL,
    grade           VARCHAR(30)     DEFAULT NULL,
    academic_year   VARCHAR(20)     NOT NULL,
    is_current      BOOLEAN      NOT NULL DEFAULT 1,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_dependent_id (dependent_id),
    INDEX idx_academic_year (academic_year),
    CONSTRAINT fk_edu_dependent FOREIGN KEY (dependent_id) REFERENCES emp_dependent(id) ON DELETE RESTRICT
);

-- EMP-08: 福利金扣繳歷史
CREATE TABLE IF NOT EXISTS emp_contribution_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    contribution_year VARCHAR(10)   NOT NULL,
    contribution_month VARCHAR(10)  NOT NULL,
    amount          DECIMAL(12)  NOT NULL,
    deduction_status VARCHAR(30)    NOT NULL DEFAULT 'deducted',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_contribution_year (contribution_year),
    UNIQUE (employee_id, contribution_year, contribution_month),
    CONSTRAINT fk_contribution_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT
);

-- EMP-09: 資格快照
CREATE TABLE IF NOT EXISTS emp_eligibility_snapshot (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    snapshot_date   DATE            NOT NULL,
    snapshot_type   VARCHAR(30)     NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    tenure_years    INT             DEFAULT NULL,
    contribution_months INT         DEFAULT NULL,
    eligibility_json JSONB           DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_snapshot_date (snapshot_date),
    INDEX idx_snapshot_type (snapshot_type),
    CONSTRAINT fk_eligibility_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT
);

-- EMP-10: 資料變更差異
CREATE TABLE IF NOT EXISTS emp_profile_change (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    change_type     VARCHAR(30)     NOT NULL,
    before_json     JSONB            DEFAULT NULL,
    after_json      JSONB            NOT NULL,
    changed_by      BIGINT DEFAULT NULL,
    change_reason   VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_change_type (change_type),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_profile_change_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT
);

-- EMP-11: 資料導入關聯
CREATE TABLE IF NOT EXISTS emp_data_import_link (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    import_job_id   BIGINT NOT NULL,
    source_row      INT             DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (employee_id, import_job_id),
    INDEX idx_import_job_id (import_job_id),
    CONSTRAINT fk_import_link_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT,
    CONSTRAINT fk_import_link_job FOREIGN KEY (import_job_id) REFERENCES sys_import_job(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 任職記錄（原 ORG 模組，因 FK 依賴 emp_employee 移入此處）
-- ============================================================================

-- EMP-12: 任職記錄
CREATE TABLE IF NOT EXISTS org_assignment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     BIGINT NOT NULL,
    org_unit_id     BIGINT NOT NULL,
    position_id     BIGINT DEFAULT NULL,
    job_title       VARCHAR(100)    DEFAULT NULL,
    is_primary      BOOLEAN      NOT NULL DEFAULT 0,
    is_manager      BOOLEAN      NOT NULL DEFAULT 0,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_org_unit_id (org_unit_id),
    INDEX idx_position_id (position_id),
    KEY idx_is_primary (is_primary),
    INDEX idx_effective (effective_date, expiration_date),
    CONSTRAINT fk_assignment_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT,
    CONSTRAINT fk_assignment_org FOREIGN KEY (org_unit_id) REFERENCES org_unit(id) ON DELETE RESTRICT,
    CONSTRAINT fk_assignment_position FOREIGN KEY (position_id) REFERENCES org_position(id) ON DELETE SET NULL
);

-- EMP-13: 任職業務範圍
CREATE TABLE IF NOT EXISTS org_assignment_scope (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id   BIGINT NOT NULL,
    scope_type      VARCHAR(30)     NOT NULL,
    scope_id        BIGINT NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (assignment_id, scope_type, scope_id),
    INDEX idx_scope_type (scope_type, scope_id),
    CONSTRAINT fk_scope_assignment FOREIGN KEY (assignment_id) REFERENCES org_assignment(id) ON DELETE RESTRICT
);
