-- ============================================================================
-- 台鐵職工福利平台 — IAM 身份認證模組
-- 模組：05_iam.sql
-- 說明：帳號、身份提供方、外部身份、密碼摘要、啟用挑戰、OTP、MFA、登入紀錄、會話、鎖定
-- 依賴：01_sys.sql、04_emp.sql
-- 設計原則：不保存 Microsoft Graph 密碼、OTP 只存摘要、密碼使用專用哈希演算法
-- ============================================================================

-- schema via search_path

-- IAM-01: 身份提供方
CREATE TABLE IF NOT EXISTS iam_identity_provider (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider_code   VARCHAR(50)     NOT NULL,
    provider_name   VARCHAR(100)    NOT NULL,
    provider_type   VARCHAR(30)     NOT NULL,
    config_json     JSONB            DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (provider_code)
);

-- IAM-02: 平台帳號
CREATE TABLE IF NOT EXISTS iam_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username        VARCHAR(100)    NOT NULL,
    employee_id     BIGINT DEFAULT NULL,
    display_name    VARCHAR(100)    NOT NULL,
    email           VARCHAR(200)    DEFAULT NULL,
    account_status  VARCHAR(30)     NOT NULL DEFAULT 'pending_activation',
    login_failures  INT             NOT NULL DEFAULT 0,
    last_login_at   TIMESTAMP(6)     DEFAULT NULL,
    last_login_ip   VARCHAR(45)     DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (username),
    INDEX idx_employee_id (employee_id),
    INDEX idx_account_status (account_status),
    INDEX idx_email (email),
    CONSTRAINT fk_account_employee FOREIGN KEY (employee_id) REFERENCES emp_employee(id) ON DELETE SET NULL
);

-- IAM-03: 外部身份綁定
CREATE TABLE IF NOT EXISTS iam_external_identity (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    provider_id     BIGINT NOT NULL,
    subject         VARCHAR(200)    NOT NULL,
    external_username VARCHAR(100)  DEFAULT NULL,
    is_primary      BOOLEAN      NOT NULL DEFAULT 0,
    last_sync_at    TIMESTAMP(6)     DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (provider_id, subject),
    INDEX idx_account_id (account_id),
    CONSTRAINT fk_external_identity_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT,
    CONSTRAINT fk_external_identity_provider FOREIGN KEY (provider_id) REFERENCES iam_identity_provider(id) ON DELETE RESTRICT
);

-- IAM-04: 帳號密碼憑證
CREATE TABLE IF NOT EXISTS iam_password_credential (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    hash_algorithm  VARCHAR(30)     NOT NULL DEFAULT 'argon2id',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (account_id),
    CONSTRAINT fk_password_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- IAM-05: 首次啟用挑戰
CREATE TABLE IF NOT EXISTS iam_activation_challenge (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    challenge_token VARCHAR(64)     NOT NULL,
    token_hash      VARCHAR(255)    NOT NULL,
    challenge_type  VARCHAR(30)     NOT NULL DEFAULT 'email',
    expires_at      TIMESTAMP(6)     NOT NULL,
    is_used         BOOLEAN      NOT NULL DEFAULT 0,
    used_at         TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_token_hash (token_hash),
    CONSTRAINT fk_activation_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- IAM-06: OTP 挑戰
CREATE TABLE IF NOT EXISTS iam_otp_challenge (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    otp_hash        VARCHAR(255)    NOT NULL,
    purpose         VARCHAR(30)     NOT NULL,
    expires_at      TIMESTAMP(6)     NOT NULL,
    max_attempts    INT             NOT NULL DEFAULT 5,
    attempt_count   INT             NOT NULL DEFAULT 0,
    is_used         BOOLEAN      NOT NULL DEFAULT 0,
    used_at         TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_purpose (purpose),
    CONSTRAINT fk_otp_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- IAM-07: MFA 因子
CREATE TABLE IF NOT EXISTS iam_mfa_factor (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    factor_type     VARCHAR(30)     NOT NULL,
    factor_key_hash VARCHAR(255)    DEFAULT NULL,
    is_verified     BOOLEAN      NOT NULL DEFAULT 0,
    is_primary      BOOLEAN      NOT NULL DEFAULT 0,
    verified_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    CONSTRAINT fk_mfa_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- IAM-08: 登入嘗試記錄
CREATE TABLE IF NOT EXISTS iam_login_attempt (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT DEFAULT NULL,
    username        VARCHAR(100)    NOT NULL,
    attempt_result  VARCHAR(30)     NOT NULL,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    user_agent      VARCHAR(500)    DEFAULT NULL,
    risk_score      INT             DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_username (username),
    INDEX idx_attempt_result (attempt_result),
    INDEX idx_created_at (created_at)
);

-- IAM-09: 登入會話
CREATE TABLE IF NOT EXISTS iam_session (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    session_token   VARCHAR(255)    NOT NULL,
    refresh_token_hash VARCHAR(255) DEFAULT NULL,
    device_info     VARCHAR(500)    DEFAULT NULL,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    is_revoked      BOOLEAN      NOT NULL DEFAULT 0,
    revoked_at      TIMESTAMP(6)     DEFAULT NULL,
    idle_timeout_seconds INT        NOT NULL DEFAULT 1800,
    last_activity_at TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMP(6)     NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_session_token (session_token),
    INDEX idx_is_revoked (is_revoked),
    INDEX idx_expires_at (expires_at),
    CONSTRAINT fk_session_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- IAM-10: 帳號鎖定記錄
CREATE TABLE IF NOT EXISTS iam_account_lock (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    lock_reason     VARCHAR(30)     NOT NULL,
    lock_details    VARCHAR(500)    DEFAULT NULL,
    locked_by       BIGINT DEFAULT NULL,
    locked_at       TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unlock_at       TIMESTAMP(6)     DEFAULT NULL,
    unlocked_by     BIGINT DEFAULT NULL,
    unlocked_at     TIMESTAMP(6)     DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_locked_at (locked_at),
    CONSTRAINT fk_lock_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- IAM-11: 密碼歷史（防止重複使用）
CREATE TABLE IF NOT EXISTS iam_password_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    hash_algorithm  VARCHAR(30)     NOT NULL DEFAULT 'argon2id',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_password_history_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- IAM-12: 使用者同意記錄
CREATE TABLE IF NOT EXISTS iam_user_consent (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    consent_type    VARCHAR(50)     NOT NULL,
    consent_version VARCHAR(30)     NOT NULL,
    ip_address      VARCHAR(45)     DEFAULT NULL,
    request_trace   VARCHAR(64)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (account_id, consent_type, consent_version),
    INDEX idx_consent_type (consent_type),
    CONSTRAINT fk_consent_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);
