-- ============================================================================
-- 台鐵職工福利平台 — RBAC 權限控制模組
-- 模組：06_rbac.sql
-- 說明：角色、權限、角色-權限關係、授權、資料範圍、業務範圍、代理、變更申請與歷史
-- 依賴：01_sys.sql、03_org.sql、04_emp.sql、05_iam.sql
-- 設計原則：可配置 RBAC、角色名稱不承載資料範圍、系統管理與業務審批權限分離
-- ============================================================================

-- schema via search_path

-- RBAC-01: 角色
CREATE TABLE IF NOT EXISTS rbac_role (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_code       VARCHAR(50)     NOT NULL,
    role_name       VARCHAR(100)    NOT NULL,
    role_type       VARCHAR(30)     NOT NULL DEFAULT 'business',
    description     VARCHAR(500)    DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (role_code)
);

-- RBAC-02: 權限
CREATE TABLE IF NOT EXISTS rbac_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    permission_code VARCHAR(100)    NOT NULL,
    permission_name VARCHAR(100)    NOT NULL,
    module_code     VARCHAR(30)     NOT NULL,
    resource_type   VARCHAR(50)     DEFAULT NULL,
    action          VARCHAR(30)     NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (permission_code),
    INDEX idx_module_code (module_code)
);

-- RBAC-03: 角色-權限關係
CREATE TABLE IF NOT EXISTS rbac_role_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_id         BIGINT NOT NULL,
    permission_id   BIGINT NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (role_id, permission_id),
    INDEX idx_permission_id (permission_id),
    CONSTRAINT fk_role_perm_role FOREIGN KEY (role_id) REFERENCES rbac_role(id) ON DELETE RESTRICT,
    CONSTRAINT fk_role_perm_permission FOREIGN KEY (permission_id) REFERENCES rbac_permission(id) ON DELETE RESTRICT
);

-- RBAC-04: 角色授權
CREATE TABLE IF NOT EXISTS rbac_role_assignment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    role_id         BIGINT NOT NULL,
    effective_date  TIMESTAMP(6)     NOT NULL,
    expiration_date TIMESTAMP(6)     DEFAULT NULL,
    revoked_at      TIMESTAMP(6)     DEFAULT NULL,
    granted_by      BIGINT DEFAULT NULL,
    grant_reason    VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_role_id (role_id),
    INDEX idx_effective_date (effective_date),
    CONSTRAINT fk_role_assign_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT,
    CONSTRAINT fk_role_assign_role FOREIGN KEY (role_id) REFERENCES rbac_role(id) ON DELETE RESTRICT
);

-- RBAC-05: 資料範圍定義
CREATE TABLE IF NOT EXISTS rbac_data_scope (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    scope_code      VARCHAR(50)     NOT NULL,
    scope_name      VARCHAR(100)    NOT NULL,
    scope_type      VARCHAR(30)     NOT NULL,
    description     VARCHAR(500)    DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (scope_code)
);

-- RBAC-06: 授權資料範圍
CREATE TABLE IF NOT EXISTS rbac_assignment_scope (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id   BIGINT NOT NULL,
    data_scope_id   BIGINT NOT NULL,
    scope_object_type VARCHAR(30)   DEFAULT NULL,
    scope_object_id BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (assignment_id, data_scope_id, scope_object_type, scope_object_id),
    INDEX idx_data_scope_id (data_scope_id),
    INDEX idx_scope_object (scope_object_type, scope_object_id),
    CONSTRAINT fk_assign_scope_assignment FOREIGN KEY (assignment_id) REFERENCES rbac_role_assignment(id) ON DELETE RESTRICT,
    CONSTRAINT fk_assign_scope_data FOREIGN KEY (data_scope_id) REFERENCES rbac_data_scope(id) ON DELETE RESTRICT
);

-- RBAC-07: 業務範圍
CREATE TABLE IF NOT EXISTS rbac_business_scope (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id   BIGINT NOT NULL,
    scope_type      VARCHAR(30)     NOT NULL,
    scope_id        BIGINT NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (assignment_id, scope_type, scope_id),
    INDEX idx_scope_type (scope_type, scope_id),
    CONSTRAINT fk_biz_scope_assignment FOREIGN KEY (assignment_id) REFERENCES rbac_role_assignment(id) ON DELETE RESTRICT
);

-- RBAC-08: 臨時職務／權限代理
CREATE TABLE IF NOT EXISTS rbac_delegation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    delegator_id    BIGINT NOT NULL,
    delegate_id     BIGINT NOT NULL,
    delegation_type VARCHAR(30)     NOT NULL,
    role_id         BIGINT DEFAULT NULL,
    effective_date  TIMESTAMP(6)     NOT NULL,
    expiration_date TIMESTAMP(6)     DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    reason          VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_delegator_id (delegator_id),
    INDEX idx_delegate_id (delegate_id),
    INDEX idx_is_active (is_active, effective_date, expiration_date),
    CONSTRAINT fk_delegation_delegator FOREIGN KEY (delegator_id) REFERENCES iam_account(id) ON DELETE RESTRICT,
    CONSTRAINT fk_delegation_delegate FOREIGN KEY (delegate_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- RBAC-09: 高權限變更申請
CREATE TABLE IF NOT EXISTS rbac_change_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_no      VARCHAR(50)     NOT NULL,
    request_type    VARCHAR(30)     NOT NULL,
    target_account_id BIGINT NOT NULL,
    role_id         BIGINT DEFAULT NULL,
    proposed_scope_json JSONB       DEFAULT NULL,
    reason          TEXT            NOT NULL,
    request_status  VARCHAR(30)     NOT NULL DEFAULT 'pending',
    requested_by    BIGINT NOT NULL,
    approved_by     BIGINT DEFAULT NULL,
    approved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (request_no),
    INDEX idx_target_account (target_account_id),
    INDEX idx_request_status (request_status)
);

-- RBAC-10: 權限變更歷史
CREATE TABLE IF NOT EXISTS rbac_change_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    change_request_id BIGINT DEFAULT NULL,
    change_type     VARCHAR(30)     NOT NULL,
    account_id      BIGINT NOT NULL,
    before_json     JSONB            DEFAULT NULL,
    after_json      JSONB            NOT NULL,
    changed_by      BIGINT NOT NULL,
    change_reason   VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_change_request_id (change_request_id),
    INDEX idx_created_at (created_at)
);
