-- ============================================================================
-- 台鐵職工福利平台 — NTF 通知服務模組
-- 模組：07_ntf.sql
-- 說明：通知模板、模板版本、業務消息、收件人、渠道發送、站內信箱、Web Push、偏好與重試
-- 依賴：01_sys.sql、05_iam.sql
-- 設計原則：業務模組只產生通知意圖，不保存渠道發送細節；消息引用模板版本
-- ============================================================================

-- schema via search_path

-- NTF-01: 通知模板主檔
CREATE TABLE IF NOT EXISTS ntf_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_code   VARCHAR(50)     NOT NULL,
    template_name   VARCHAR(100)    NOT NULL,
    template_type   VARCHAR(30)     NOT NULL,
    category        VARCHAR(50)     DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_code)
);

-- NTF-02: 通知模板版本
CREATE TABLE IF NOT EXISTS ntf_template_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_id     BIGINT NOT NULL,
    version_no      INT             NOT NULL,
    subject         VARCHAR(200)    DEFAULT NULL,
    body_template   TEXT            NOT NULL,
    content_type    VARCHAR(30)     NOT NULL DEFAULT 'text/plain',
    variables_json  JSONB            DEFAULT NULL,
    is_published    BOOLEAN      NOT NULL DEFAULT 0,
    published_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_id, version_no),
    CONSTRAINT fk_template_version_template FOREIGN KEY (template_id) REFERENCES ntf_template(id) ON DELETE RESTRICT
);

-- NTF-03: 業務通知消息
CREATE TABLE IF NOT EXISTS ntf_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_code    VARCHAR(64)     NOT NULL,
    template_version_id BIGINT NOT NULL,
    aggregate_type  VARCHAR(50)     DEFAULT NULL,
    aggregate_id    BIGINT DEFAULT NULL,
    payload_json    JSONB            DEFAULT NULL,
    sender_type     VARCHAR(30)     NOT NULL DEFAULT 'system',
    sender_id       BIGINT DEFAULT NULL,
    priority        VARCHAR(10)     NOT NULL DEFAULT 'normal',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (message_code),
    INDEX idx_aggregate (aggregate_type, aggregate_id),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_message_template_version FOREIGN KEY (template_version_id) REFERENCES ntf_template_version(id) ON DELETE RESTRICT
);

-- NTF-04: 消息收件人
CREATE TABLE IF NOT EXISTS ntf_recipient (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id      BIGINT NOT NULL,
    account_id      BIGINT DEFAULT NULL,
    recipient_name  VARCHAR(100)    DEFAULT NULL,
    recipient_address VARCHAR(255)  DEFAULT NULL,
    required_channels VARCHAR(100)  NOT NULL DEFAULT 'in_app',
    is_processed    BOOLEAN      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_message_id (message_id),
    INDEX idx_account_id (account_id),
    CONSTRAINT fk_recipient_message FOREIGN KEY (message_id) REFERENCES ntf_message(id) ON DELETE RESTRICT
);

-- NTF-05: 渠道發送記錄
CREATE TABLE IF NOT EXISTS ntf_delivery (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recipient_id    BIGINT NOT NULL,
    channel         VARCHAR(30)     NOT NULL,
    delivery_status VARCHAR(30)     NOT NULL DEFAULT 'pending',
    attempt_count   INT             NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMP(6)     DEFAULT NULL,
    error_message   TEXT            DEFAULT NULL,
    provider_message_id VARCHAR(200) DEFAULT NULL,
    delivered_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_recipient_id (recipient_id),
    INDEX idx_delivery_status (delivery_status),
    INDEX idx_channel (channel),
    CONSTRAINT fk_delivery_recipient FOREIGN KEY (recipient_id) REFERENCES ntf_recipient(id) ON DELETE RESTRICT
);

-- NTF-06: 站內通知／已讀
CREATE TABLE IF NOT EXISTS ntf_inbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    delivery_id     BIGINT DEFAULT NULL,
    title           VARCHAR(200)    NOT NULL,
    body            TEXT            NOT NULL,
    is_read         BOOLEAN      NOT NULL DEFAULT 0,
    read_at         TIMESTAMP(6)     DEFAULT NULL,
    is_archived     BOOLEAN      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_is_read (is_read),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_inbox_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- NTF-07: Web Push 推播訂閱
CREATE TABLE IF NOT EXISTS ntf_web_push_subscription (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    endpoint        VARCHAR(500)    NOT NULL,
    p256dh_key      VARCHAR(200)    NOT NULL,
    auth_key        VARCHAR(100)    NOT NULL,
    user_agent      VARCHAR(500)    DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_is_active (is_active),
    CONSTRAINT fk_push_subscription_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- NTF-08: 使用者通知偏好
CREATE TABLE IF NOT EXISTS ntf_user_preference (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    category        VARCHAR(50)     NOT NULL,
    channel         VARCHAR(30)     NOT NULL,
    is_enabled      BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (account_id, category, channel),
    CONSTRAINT fk_preference_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- NTF-09: 失敗通知重送任務
CREATE TABLE IF NOT EXISTS ntf_retry_job (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    delivery_id     BIGINT NOT NULL,
    retry_status    VARCHAR(30)     NOT NULL DEFAULT 'pending',
    retry_count     INT             NOT NULL DEFAULT 0,
    max_retries     INT             NOT NULL DEFAULT 3,
    next_retry_at   TIMESTAMP(6)     DEFAULT NULL,
    last_error      TEXT            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_delivery_id (delivery_id),
    INDEX idx_retry_status (retry_status),
    CONSTRAINT fk_retry_delivery FOREIGN KEY (delivery_id) REFERENCES ntf_delivery(id) ON DELETE RESTRICT
);
