-- ============================================================================
-- 台鐵職工福利平台 — BEN-CFG 補助配置模組
-- 模組：08_ben_config.sql
-- 說明：補助目錄、政策版本、動態表單定義與版本、JSONB 索引、應附文件規則、資格規則、
--       額度規則、數位切結、列印模板、會計映射、工作流映射
-- 依賴：01_sys.sql、02_file.sql、10_workflow.sql（workflow_mapping 外鍵）
-- 設計原則：已發佈版本不可覆蓋、歷史案件引用提交時版本
-- ============================================================================

-- schema via search_path

-- ============================================================================
-- 1. 補助目錄與政策
-- ============================================================================

-- BEN-CFG-01: 補助大項目錄
CREATE TABLE IF NOT EXISTS ben_program (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    program_code    VARCHAR(30)     NOT NULL,
    program_name    VARCHAR(100)    NOT NULL,
    program_type    VARCHAR(30)     NOT NULL DEFAULT 'subsidy',
    sort_order      INT             NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (program_code)
);

-- BEN-CFG-02: 具體補助類型
CREATE TABLE IF NOT EXISTS ben_type (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type_code       VARCHAR(30)     NOT NULL,
    type_name       VARCHAR(100)    NOT NULL,
    program_id      BIGINT NOT NULL,
    sort_order      INT             NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (type_code),
    INDEX idx_program_id (program_id),
    CONSTRAINT fk_type_program FOREIGN KEY (program_id) REFERENCES ben_program(id) ON DELETE RESTRICT
);

-- BEN-CFG-03: 補助政策版本
CREATE TABLE IF NOT EXISTS ben_policy_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    benefit_type_id BIGINT NOT NULL,
    version_no      INT             NOT NULL,
    policy_name     VARCHAR(200)    NOT NULL,
    description     TEXT            DEFAULT NULL,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    is_published    BOOLEAN      NOT NULL DEFAULT 0,
    published_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (benefit_type_id, version_no),
    INDEX idx_effective_date (effective_date, expiration_date),
    CONSTRAINT fk_policy_type FOREIGN KEY (benefit_type_id) REFERENCES ben_type(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 2. 動態表單定義
-- ============================================================================

-- BEN-CFG-04: 動態表單邏輯名稱
CREATE TABLE IF NOT EXISTS ben_form_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    form_code       VARCHAR(50)     NOT NULL,
    form_name       VARCHAR(100)    NOT NULL,
    benefit_type_id BIGINT DEFAULT NULL,
    description     TEXT            DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (form_code),
    INDEX idx_benefit_type_id (benefit_type_id)
);

-- BEN-CFG-05: 表單版本
CREATE TABLE IF NOT EXISTS ben_form_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    form_definition_id BIGINT NOT NULL,
    version_no      INT             NOT NULL,
    schema_json     JSONB            NOT NULL,
    ui_schema_json  JSONB            DEFAULT NULL,
    validation_json JSONB            DEFAULT NULL,
    schema_hash     VARCHAR(64)     NOT NULL,
    is_published    BOOLEAN      NOT NULL DEFAULT 0,
    published_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (form_definition_id, version_no),
    CONSTRAINT fk_form_version_definition FOREIGN KEY (form_definition_id) REFERENCES ben_form_definition(id) ON DELETE RESTRICT
);

-- BEN-CFG-06: JSONB 索引定義
CREATE TABLE IF NOT EXISTS ben_form_index_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    form_version_id BIGINT NOT NULL,
    json_path       VARCHAR(200)    NOT NULL,
    target_type     VARCHAR(30)     NOT NULL,
    is_stable       BOOLEAN      NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (form_version_id, json_path),
    CONSTRAINT fk_index_definition_form FOREIGN KEY (form_version_id) REFERENCES ben_form_version(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 3. 規則與模板
-- ============================================================================

-- BEN-CFG-07: 應附文件規則
CREATE TABLE IF NOT EXISTS ben_required_document_rule (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_version_id   BIGINT NOT NULL,
    document_type_code  VARCHAR(50)     NOT NULL,
    document_name       VARCHAR(100)    NOT NULL,
    is_required         BOOLEAN      NOT NULL DEFAULT 1,
    max_files           INT             NOT NULL DEFAULT 1,
    condition_json      JSONB            DEFAULT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_policy_version_id (policy_version_id),
    CONSTRAINT fk_document_rule_policy FOREIGN KEY (policy_version_id) REFERENCES ben_policy_version(id) ON DELETE RESTRICT
);

-- BEN-CFG-08: 資格規則
CREATE TABLE IF NOT EXISTS ben_eligibility_rule (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_version_id   BIGINT NOT NULL,
    rule_code           VARCHAR(50)     NOT NULL,
    rule_name           VARCHAR(100)    NOT NULL,
    rule_type           VARCHAR(30)     NOT NULL,
    condition_json      JSONB            NOT NULL,
    error_message       VARCHAR(500)    DEFAULT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (policy_version_id, rule_code),
    CONSTRAINT fk_eligibility_rule_policy FOREIGN KEY (policy_version_id) REFERENCES ben_policy_version(id) ON DELETE RESTRICT
);

-- BEN-CFG-09: 額度規則
CREATE TABLE IF NOT EXISTS ben_limit_rule (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_version_id   BIGINT NOT NULL,
    limit_type          VARCHAR(30)     NOT NULL,
    limit_value         DECIMAL(12)  NOT NULL,
    currency_code       VARCHAR(3)      NOT NULL DEFAULT 'TWD',
    condition_json      JSONB            DEFAULT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_policy_version_id (policy_version_id),
    CONSTRAINT fk_limit_rule_policy FOREIGN KEY (policy_version_id) REFERENCES ben_policy_version(id) ON DELETE RESTRICT
);

-- BEN-CFG-10: 數位切結模板
CREATE TABLE IF NOT EXISTS ben_declaration_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_version_id BIGINT NOT NULL,
    version_no      INT             NOT NULL,
    content         TEXT            NOT NULL,
    is_published    BOOLEAN      NOT NULL DEFAULT 0,
    published_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (policy_version_id, version_no),
    CONSTRAINT fk_declaration_policy FOREIGN KEY (policy_version_id) REFERENCES ben_policy_version(id) ON DELETE RESTRICT
);

-- BEN-CFG-11: 正式申請書列印模板
CREATE TABLE IF NOT EXISTS ben_print_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_version_id BIGINT NOT NULL,
    version_no      INT             NOT NULL,
    template_file_key VARCHAR(128)  DEFAULT NULL,
    template_type   VARCHAR(30)     NOT NULL DEFAULT 'pdf',
    is_published    BOOLEAN      NOT NULL DEFAULT 0,
    published_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (policy_version_id, version_no),
    CONSTRAINT fk_print_policy FOREIGN KEY (policy_version_id) REFERENCES ben_policy_version(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 4. 映射
-- ============================================================================

-- BEN-CFG-12: 補助類型與會計科目映射
CREATE TABLE IF NOT EXISTS ben_accounting_mapping (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_version_id   BIGINT NOT NULL,
    voucher_type        VARCHAR(30)     NOT NULL,
    debit_subject_code  VARCHAR(50)     DEFAULT NULL,
    credit_subject_code VARCHAR(50)     DEFAULT NULL,
    is_active           BOOLEAN      NOT NULL DEFAULT 1,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_policy_version_id (policy_version_id),
    CONSTRAINT fk_accounting_mapping_policy FOREIGN KEY (policy_version_id) REFERENCES ben_policy_version(id) ON DELETE RESTRICT
);

-- BEN-CFG-13: 補助類型與工作流映射
CREATE TABLE IF NOT EXISTS ben_workflow_mapping (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_version_id   BIGINT NOT NULL,
    wf_template_id      BIGINT NOT NULL,
    min_amount          DECIMAL(12)  DEFAULT NULL,
    max_amount          DECIMAL(12)  DEFAULT NULL,
    org_unit_id         BIGINT DEFAULT NULL,
    is_active           BOOLEAN      NOT NULL DEFAULT 1,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_policy_version_id (policy_version_id),
    INDEX idx_wf_template_id (wf_template_id),
    CONSTRAINT fk_workflow_mapping_policy FOREIGN KEY (policy_version_id) REFERENCES ben_policy_version(id) ON DELETE RESTRICT
);
