-- ============================================================================
-- 台鐵職工福利平台 — BEN-APP 補助申請模組
-- 模組：09_ben_application.sql
-- 說明：案件主檔、表單資料、申請快照、參與方、附件、切結、狀態歷史、驗證、
--       補件要求與補交、紙本檢查點、業務鎖、滿意度回饋、封存
-- 依賴：01_sys.sql、02_file.sql、04_emp.sql、05_iam.sql、08_ben_config.sql
-- 設計原則：申請人與填表人分列、提交時產生不可變快照、補件不覆蓋原始資料
-- ============================================================================

-- schema via search_path

-- ============================================================================
-- 1. 申請核心
-- ============================================================================

-- BEN-APP-01: 案件主檔
CREATE TABLE IF NOT EXISTS ben_application (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_no      VARCHAR(50)     NOT NULL,
    benefit_program_id  BIGINT NOT NULL,
    benefit_type_id     BIGINT NOT NULL,
    policy_version_id   BIGINT NOT NULL,
    form_version_id     BIGINT NOT NULL,
    applicant_employee_id BIGINT NOT NULL,
    entered_by_account_id BIGINT NOT NULL,
    is_proxy_entry      BOOLEAN      NOT NULL DEFAULT 0,
    org_unit_id         BIGINT DEFAULT NULL,
    welfare_branch_id   BIGINT DEFAULT NULL,
    requested_amount    DECIMAL(12)  NOT NULL DEFAULT 0,
    approved_amount     DECIMAL(12)  DEFAULT NULL,
    currency_code       VARCHAR(3)      NOT NULL DEFAULT 'TWD',
    application_year    VARCHAR(10)     NOT NULL,
    submitted_at        TIMESTAMP(6)     DEFAULT NULL,
    approved_at         TIMESTAMP(6)     DEFAULT NULL,
    closed_at           TIMESTAMP(6)     DEFAULT NULL,
    current_status      VARCHAR(30)     NOT NULL DEFAULT 'draft',
    current_stage       VARCHAR(30)     DEFAULT NULL,
    row_version         INT             NOT NULL DEFAULT 1,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (application_no),
    INDEX idx_applicant (applicant_employee_id, submitted_at),
    INDEX idx_type_year (benefit_type_id, application_year, current_status),
    INDEX idx_welfare_status (welfare_branch_id, current_status, submitted_at),
    INDEX idx_entered_by (entered_by_account_id, is_proxy_entry, submitted_at),
    INDEX idx_current_status (current_status),
    CONSTRAINT fk_app_program FOREIGN KEY (benefit_program_id) REFERENCES ben_program(id) ON DELETE RESTRICT,
    CONSTRAINT fk_app_type FOREIGN KEY (benefit_type_id) REFERENCES ben_type(id) ON DELETE RESTRICT,
    CONSTRAINT fk_app_policy FOREIGN KEY (policy_version_id) REFERENCES ben_policy_version(id) ON DELETE RESTRICT,
    CONSTRAINT fk_app_form FOREIGN KEY (form_version_id) REFERENCES ben_form_version(id) ON DELETE RESTRICT,
    CONSTRAINT fk_app_employee FOREIGN KEY (applicant_employee_id) REFERENCES emp_employee(id) ON DELETE RESTRICT,
    CONSTRAINT fk_app_entered_by FOREIGN KEY (entered_by_account_id) REFERENCES iam_account(id) ON DELETE RESTRICT,
    CONSTRAINT fk_app_org FOREIGN KEY (org_unit_id) REFERENCES org_unit(id) ON DELETE SET NULL,
    CONSTRAINT fk_app_welfare FOREIGN KEY (welfare_branch_id) REFERENCES org_unit(id) ON DELETE SET NULL
);

-- BEN-APP-02: 表單提交資料
CREATE TABLE IF NOT EXISTS ben_application_form_data (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id      BIGINT NOT NULL,
    form_version_id     BIGINT NOT NULL,
    schema_hash         VARCHAR(64)     NOT NULL,
    form_data_json      JSONB            NOT NULL,
    is_current          BOOLEAN      NOT NULL DEFAULT 1,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    INDEX idx_is_current (is_current),
    CONSTRAINT fk_form_data_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT,
    CONSTRAINT fk_form_data_version FOREIGN KEY (form_version_id) REFERENCES ben_form_version(id) ON DELETE RESTRICT
);

-- BEN-APP-03: 申請快照（提交時固化）
CREATE TABLE IF NOT EXISTS ben_application_snapshot (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id      BIGINT NOT NULL,
    snapshot_type       VARCHAR(30)     NOT NULL,
    snapshot_json       JSONB            NOT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    INDEX idx_snapshot_type (snapshot_type),
    CONSTRAINT fk_snapshot_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- BEN-APP-04: 案件參與方
CREATE TABLE IF NOT EXISTS ben_application_party (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    party_type      VARCHAR(30)     NOT NULL,
    employee_id     BIGINT DEFAULT NULL,
    dependent_id    BIGINT DEFAULT NULL,
    party_name      VARCHAR(100)    NOT NULL,
    party_detail_json JSONB         DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    INDEX idx_party_type (party_type),
    CONSTRAINT fk_party_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 2. 附件、切結與紙本檢查點
-- ============================================================================

-- BEN-APP-05: 案件附件
CREATE TABLE IF NOT EXISTS ben_application_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    file_id         BIGINT NOT NULL,
    document_type   VARCHAR(50)     NOT NULL,
    attachment_version INT         NOT NULL DEFAULT 1,
    source          VARCHAR(30)     NOT NULL DEFAULT 'applicant',
    is_current      BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    INDEX idx_file_id (file_id),
    INDEX idx_document_type (document_type),
    CONSTRAINT fk_attachment_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT,
    CONSTRAINT fk_attachment_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- BEN-APP-06: 數位切結同意
CREATE TABLE IF NOT EXISTS ben_application_declaration (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    declaration_template_id BIGINT NOT NULL,
    agreed_by       BIGINT DEFAULT NULL,
    agreed_at       TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    request_trace   VARCHAR(64)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    CONSTRAINT fk_declaration_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT,
    CONSTRAINT fk_declaration_template FOREIGN KEY (declaration_template_id) REFERENCES ben_declaration_template(id) ON DELETE RESTRICT
);

-- BEN-APP-07: 紙本核章檢查點
CREATE TABLE IF NOT EXISTS ben_physical_checkpoint (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    checkpoint_type VARCHAR(30)     NOT NULL,
    checkpoint_order INT            NOT NULL,
    is_completed    BOOLEAN      NOT NULL DEFAULT 0,
    completed_by    BIGINT DEFAULT NULL,
    completed_at    TIMESTAMP(6)     DEFAULT NULL,
    remark          VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    INDEX idx_checkpoint_type (checkpoint_type),
    CONSTRAINT fk_checkpoint_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- BEN-APP-08: 業務鎖
CREATE TABLE IF NOT EXISTS ben_application_lock (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    lock_type       VARCHAR(30)     NOT NULL,
    lock_source     VARCHAR(50)     NOT NULL,
    locked_by       BIGINT DEFAULT NULL,
    locked_at       TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unlocked_by     BIGINT DEFAULT NULL,
    unlocked_at     TIMESTAMP(6)     DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    INDEX idx_lock_type (lock_type),
    CONSTRAINT fk_lock_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 3. 狀態歷史、驗證、補件、回饋與封存
-- ============================================================================

-- BEN-APP-09: 案件狀態歷史
CREATE TABLE IF NOT EXISTS ben_application_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    from_status     VARCHAR(30)     DEFAULT NULL,
    to_status       VARCHAR(30)     NOT NULL,
    action_type     VARCHAR(30)     NOT NULL,
    operator_id     BIGINT DEFAULT NULL,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    request_trace   VARCHAR(64)     DEFAULT NULL,
    remark          VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    INDEX idx_to_status (to_status),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_status_history_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- BEN-APP-10: 驗證結果
CREATE TABLE IF NOT EXISTS ben_application_validation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id      BIGINT NOT NULL,
    validation_type     VARCHAR(30)     NOT NULL,
    rule_code           VARCHAR(50)     DEFAULT NULL,
    rule_version_id     BIGINT DEFAULT NULL,
    result_status       VARCHAR(30)     NOT NULL,
    evidence_json       JSONB            DEFAULT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    INDEX idx_validation_type (validation_type),
    CONSTRAINT fk_validation_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- BEN-APP-11: 補件要求
CREATE TABLE IF NOT EXISTS ben_supplement_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    request_no      VARCHAR(50)     NOT NULL,
    reason          TEXT            NOT NULL,
    deadline_date   DATE            NOT NULL,
    requested_by    BIGINT DEFAULT NULL,
    request_status  VARCHAR(30)     NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (request_no),
    INDEX idx_application_id (application_id),
    INDEX idx_request_status (request_status),
    CONSTRAINT fk_supplement_request_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- BEN-APP-12: 補件補交批次
CREATE TABLE IF NOT EXISTS ben_supplement_submission (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplement_request_id BIGINT NOT NULL,
    submission_no       VARCHAR(50)     NOT NULL,
    submitted_by        BIGINT DEFAULT NULL,
    submitted_at        TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (submission_no),
    INDEX idx_supplement_request_id (supplement_request_id),
    CONSTRAINT fk_supplement_submission_request FOREIGN KEY (supplement_request_id) REFERENCES ben_supplement_request(id) ON DELETE RESTRICT
);

-- BEN-APP-13: 服務回饋
CREATE TABLE IF NOT EXISTS ben_service_feedback (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    rating          SMALLINT NOT NULL,
    comment         TEXT            DEFAULT NULL,
    submitted_by    BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    CONSTRAINT fk_feedback_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- BEN-APP-14: 結案封存
CREATE TABLE IF NOT EXISTS ben_application_archive (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id      BIGINT NOT NULL,
    archive_batch_no    VARCHAR(50)     NOT NULL,
    archive_checksum    VARCHAR(64)     DEFAULT NULL,
    archived_by         BIGINT DEFAULT NULL,
    archived_at         TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (application_id),
    INDEX idx_archive_batch_no (archive_batch_no),
    CONSTRAINT fk_archive_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);
