-- ============================================================================
-- 台鐵職工福利平台 — WF 工作流模組
-- 模組：10_workflow.sql
-- 說明：流程模板、模板版本、節點定義、轉移定義、路由規則、流程實例、任務、候選人、
--       審批動作、代理、逾時事件、快照、業務橋接表
-- 依賴：01_sys.sql、04_emp.sql、05_iam.sql、06_rbac.sql
-- 設計原則：模板版本發佈後不可修改、業務模組透過專用橋接表關聯、批次核准保留獨立動作
-- ============================================================================

-- schema via search_path

-- ============================================================================
-- 1. 流程定義
-- ============================================================================

-- WF-01: 流程模板主檔
CREATE TABLE IF NOT EXISTS wf_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_code   VARCHAR(50)     NOT NULL,
    template_name   VARCHAR(100)    NOT NULL,
    description     TEXT            DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_code)
);

-- WF-02: 流程模板版本
CREATE TABLE IF NOT EXISTS wf_template_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_id     BIGINT NOT NULL,
    version_no      INT             NOT NULL,
    version_name    VARCHAR(100)    DEFAULT NULL,
    is_published    BOOLEAN      NOT NULL DEFAULT 0,
    published_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_id, version_no),
    CONSTRAINT fk_wf_template_version_template FOREIGN KEY (template_id) REFERENCES wf_template(id) ON DELETE RESTRICT
);

-- WF-03: 節點定義
CREATE TABLE IF NOT EXISTS wf_node_definition (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_version_id BIGINT NOT NULL,
    node_code           VARCHAR(50)     NOT NULL,
    node_name           VARCHAR(100)    NOT NULL,
    node_type           VARCHAR(30)     NOT NULL,
    node_order          INT             NOT NULL,
    assignment_rule_json JSONB           DEFAULT NULL,
    timeout_hours       INT             DEFAULT NULL,
    is_required         BOOLEAN      NOT NULL DEFAULT 1,
    config_json         JSONB            DEFAULT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_version_id, node_code),
    INDEX idx_node_order (template_version_id, node_order),
    CONSTRAINT fk_node_template_version FOREIGN KEY (template_version_id) REFERENCES wf_template_version(id) ON DELETE RESTRICT
);

-- WF-04: 轉移定義
CREATE TABLE IF NOT EXISTS wf_transition_definition (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_version_id BIGINT NOT NULL,
    transition_code     VARCHAR(50)     NOT NULL,
    source_node_id      BIGINT NOT NULL,
    target_node_id      BIGINT NOT NULL,
    condition_json      JSONB            DEFAULT NULL,
    sort_order          INT             NOT NULL DEFAULT 0,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_version_id, transition_code),
    INDEX idx_source_node (source_node_id),
    INDEX idx_target_node (target_node_id),
    CONSTRAINT fk_transition_template_version FOREIGN KEY (template_version_id) REFERENCES wf_template_version(id) ON DELETE RESTRICT,
    CONSTRAINT fk_transition_source FOREIGN KEY (source_node_id) REFERENCES wf_node_definition(id) ON DELETE RESTRICT,
    CONSTRAINT fk_transition_target FOREIGN KEY (target_node_id) REFERENCES wf_node_definition(id) ON DELETE RESTRICT
);

-- WF-05: 路由規則
CREATE TABLE IF NOT EXISTS wf_route_rule (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_version_id BIGINT NOT NULL,
    rule_code           VARCHAR(50)     NOT NULL,
    condition_json      JSONB            NOT NULL,
    target_node_id      BIGINT NOT NULL,
    sort_order          INT             NOT NULL DEFAULT 0,
    is_active           BOOLEAN      NOT NULL DEFAULT 1,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_version_id, rule_code),
    INDEX idx_target_node (target_node_id),
    CONSTRAINT fk_route_rule_template FOREIGN KEY (template_version_id) REFERENCES wf_template_version(id) ON DELETE RESTRICT,
    CONSTRAINT fk_route_rule_node FOREIGN KEY (target_node_id) REFERENCES wf_node_definition(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 2. 流程運行時
-- ============================================================================

-- WF-06: 流程實例
CREATE TABLE IF NOT EXISTS wf_instance (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    instance_no         VARCHAR(50)     NOT NULL,
    template_version_id BIGINT NOT NULL,
    instance_status     VARCHAR(30)     NOT NULL DEFAULT 'running',
    current_node_id     BIGINT DEFAULT NULL,
    started_by          BIGINT DEFAULT NULL,
    started_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at        TIMESTAMP(6)     DEFAULT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (instance_no),
    INDEX idx_template_version_id (template_version_id),
    INDEX idx_instance_status (instance_status),
    INDEX idx_current_node (current_node_id),
    CONSTRAINT fk_instance_template_version FOREIGN KEY (template_version_id) REFERENCES wf_template_version(id) ON DELETE RESTRICT
);

-- WF-07: 流程實例快照
CREATE TABLE IF NOT EXISTS wf_instance_snapshot (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    instance_id         BIGINT NOT NULL,
    snapshot_json       JSONB            NOT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (instance_id),
    CONSTRAINT fk_instance_snapshot_instance FOREIGN KEY (instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT
);

-- WF-08: 辦理任務
CREATE TABLE IF NOT EXISTS wf_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    instance_id         BIGINT NOT NULL,
    node_id             BIGINT NOT NULL,
    task_code           VARCHAR(50)     NOT NULL,
    assignee_account_id BIGINT DEFAULT NULL,
    original_assignee_id BIGINT DEFAULT NULL,
    task_status         VARCHAR(30)     NOT NULL DEFAULT 'ready',
    due_at              TIMESTAMP(6)     DEFAULT NULL,
    completed_at        TIMESTAMP(6)     DEFAULT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (task_code),
    INDEX idx_instance_id (instance_id),
    INDEX idx_assignee (assignee_account_id, task_status, due_at),
    INDEX idx_node_id (node_id),
    CONSTRAINT fk_task_instance FOREIGN KEY (instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_node FOREIGN KEY (node_id) REFERENCES wf_node_definition(id) ON DELETE RESTRICT
);

-- WF-09: 任務候選人
CREATE TABLE IF NOT EXISTS wf_task_candidate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id         BIGINT NOT NULL,
    candidate_type  VARCHAR(30)     NOT NULL,
    candidate_id    BIGINT NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (task_id, candidate_type, candidate_id),
    CONSTRAINT fk_candidate_task FOREIGN KEY (task_id) REFERENCES wf_task(id) ON DELETE RESTRICT
);

-- WF-10: 審批動作記錄
CREATE TABLE IF NOT EXISTS wf_action_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id         BIGINT NOT NULL,
    action_type     VARCHAR(30)     NOT NULL,
    operator_id     BIGINT DEFAULT NULL,
    comment         TEXT            DEFAULT NULL,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    request_trace   VARCHAR(64)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_task_id (task_id),
    INDEX idx_action_type (action_type),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_action_log_task FOREIGN KEY (task_id) REFERENCES wf_task(id) ON DELETE RESTRICT
);

-- WF-11: 審批代理關係
CREATE TABLE IF NOT EXISTS wf_delegation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id         BIGINT DEFAULT NULL,
    delegator_id    BIGINT NOT NULL,
    delegate_id     BIGINT NOT NULL,
    delegation_type VARCHAR(30)     NOT NULL,
    effective_date  TIMESTAMP(6)     NOT NULL,
    expiration_date TIMESTAMP(6)     DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    reason          VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_delegator_id (delegator_id),
    INDEX idx_delegate_id (delegate_id),
    INDEX idx_task_id (task_id),
    CONSTRAINT fk_wf_delegation_task FOREIGN KEY (task_id) REFERENCES wf_task(id) ON DELETE SET NULL,
    CONSTRAINT fk_wf_delegation_delegator FOREIGN KEY (delegator_id) REFERENCES iam_account(id) ON DELETE RESTRICT,
    CONSTRAINT fk_wf_delegation_delegate FOREIGN KEY (delegate_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- WF-12: 逾時事件
CREATE TABLE IF NOT EXISTS wf_timeout_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id         BIGINT NOT NULL,
    event_type      VARCHAR(30)     NOT NULL,
    event_status    VARCHAR(30)     NOT NULL DEFAULT 'pending',
    triggered_at    TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_task_id (task_id),
    INDEX idx_event_status (event_status),
    CONSTRAINT fk_timeout_task FOREIGN KEY (task_id) REFERENCES wf_task(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 3. 業務橋接表
-- ============================================================================

-- WF-13: 申請與工作流關聯
CREATE TABLE IF NOT EXISTS ben_application_workflow (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    wf_instance_id  BIGINT NOT NULL,
    workflow_purpose VARCHAR(30)    NOT NULL,
    is_current      BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (application_id, workflow_purpose),
    INDEX idx_wf_instance_id (wf_instance_id),
    CONSTRAINT fk_app_wf_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT,
    CONSTRAINT fk_app_wf_instance FOREIGN KEY (wf_instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT
);
