-- ============================================================================
-- 台鐵職工福利平台 — PAY 發款、請款與禮金模組
-- 模組：11_payment.sql
-- 說明：請款／發款批次、批次明細、狀態歷史、禮金活動、預估、名冊、結算、
--       撥款指令、撥款結果、領款確認、異議、例外處理
-- 依賴：01_sys.sql、09_ben_application.sql、04_emp.sql
-- 設計原則：批號唯一、部分失敗不回滾成功款項、已完成批次不可直接修改
-- ============================================================================

-- schema via search_path

-- ============================================================================
-- 1. 請款與發款批次
-- ============================================================================

-- PAY-01: 批次主檔
CREATE TABLE IF NOT EXISTS pay_batch (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_no        VARCHAR(50)     NOT NULL,
    batch_type      VARCHAR(30)     NOT NULL,
    org_unit_id     BIGINT DEFAULT NULL,
    welfare_shop_id BIGINT DEFAULT NULL,
    currency_code   VARCHAR(3)      NOT NULL DEFAULT 'TWD',
    total_count     INT             NOT NULL DEFAULT 0,
    total_amount    DECIMAL(14)  NOT NULL DEFAULT 0,
    batch_status    VARCHAR(30)     NOT NULL DEFAULT 'draft',
    description     VARCHAR(500)    DEFAULT NULL,
    created_by      BIGINT DEFAULT NULL,
    approved_by     BIGINT DEFAULT NULL,
    approved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (batch_no),
    INDEX idx_batch_status (batch_status, created_at),
    INDEX idx_org_unit_id (org_unit_id),
    INDEX idx_welfare_shop_id (welfare_shop_id),
    CONSTRAINT fk_batch_org FOREIGN KEY (org_unit_id) REFERENCES org_unit(id) ON DELETE SET NULL,
    CONSTRAINT fk_batch_welfare FOREIGN KEY (welfare_shop_id) REFERENCES org_unit(id) ON DELETE SET NULL
);

-- PAY-02: 批次明細
CREATE TABLE IF NOT EXISTS pay_batch_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_id        BIGINT NOT NULL,
    application_id  BIGINT NOT NULL,
    item_status     VARCHAR(30)     NOT NULL DEFAULT 'pending',
    amount          DECIMAL(12)  NOT NULL,
    remark          VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (batch_id, application_id),
    INDEX idx_application_id (application_id),
    CONSTRAINT fk_batch_item_batch FOREIGN KEY (batch_id) REFERENCES pay_batch(id) ON DELETE RESTRICT,
    CONSTRAINT fk_batch_item_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- PAY-03: 批次狀態歷史
CREATE TABLE IF NOT EXISTS pay_batch_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_id        BIGINT NOT NULL,
    from_status     VARCHAR(30)     DEFAULT NULL,
    to_status       VARCHAR(30)     NOT NULL,
    operator_id     BIGINT DEFAULT NULL,
    reason          VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_batch_id (batch_id),
    CONSTRAINT fk_batch_status_batch FOREIGN KEY (batch_id) REFERENCES pay_batch(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 2. 撥款
-- ============================================================================

-- PAY-04: 撥款指令
CREATE TABLE IF NOT EXISTS pay_disbursement (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_item_id   BIGINT DEFAULT NULL,
    application_id  BIGINT DEFAULT NULL,
    disbursement_type VARCHAR(30)   NOT NULL,
    amount          DECIMAL(12)  NOT NULL,
    currency_code   VARCHAR(3)      NOT NULL DEFAULT 'TWD',
    recipient_name  VARCHAR(100)    NOT NULL,
    recipient_id    VARCHAR(50)     DEFAULT NULL,
    disbursement_status VARCHAR(30) NOT NULL DEFAULT 'pending',
    requested_by    BIGINT DEFAULT NULL,
    approved_by     BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_batch_item_id (batch_item_id),
    INDEX idx_application_id (application_id),
    INDEX idx_disbursement_status (disbursement_status),
    CONSTRAINT fk_disbursement_batch_item FOREIGN KEY (batch_item_id) REFERENCES pay_batch_item(id) ON DELETE SET NULL
);

-- PAY-05: 撥款結果
CREATE TABLE IF NOT EXISTS pay_disbursement_result (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    disbursement_id BIGINT NOT NULL,
    result_status   VARCHAR(30)     NOT NULL,
    bank_reference  VARCHAR(200)    DEFAULT NULL,
    error_code      VARCHAR(50)     DEFAULT NULL,
    error_message   TEXT            DEFAULT NULL,
    raw_response    TEXT            DEFAULT NULL,
    processed_at    TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_disbursement_id (disbursement_id),
    INDEX idx_result_status (result_status),
    CONSTRAINT fk_result_disbursement FOREIGN KEY (disbursement_id) REFERENCES pay_disbursement(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 3. 禮金三階段
-- ============================================================================

-- PAY-06: 禮金活動
CREATE TABLE IF NOT EXISTS pay_gift_campaign (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campaign_code   VARCHAR(50)     NOT NULL,
    campaign_name   VARCHAR(100)    NOT NULL,
    gift_type       VARCHAR(30)     NOT NULL,
    festival_code   VARCHAR(30)     DEFAULT NULL,
    campaign_year   VARCHAR(10)     NOT NULL,
    campaign_status VARCHAR(30)     NOT NULL DEFAULT 'estimated',
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (campaign_code)
);

-- PAY-07: 禮金預估
CREATE TABLE IF NOT EXISTS pay_gift_estimate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campaign_id     BIGINT NOT NULL,
    estimate_type   VARCHAR(30)     NOT NULL DEFAULT 'initial',
    estimated_count INT             NOT NULL,
    unit_price      DECIMAL(10)  NOT NULL,
    total_amount    DECIMAL(14)  NOT NULL,
    calculation_basis VARCHAR(500)  DEFAULT NULL,
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_campaign_id (campaign_id),
    CONSTRAINT fk_estimate_campaign FOREIGN KEY (campaign_id) REFERENCES pay_gift_campaign(id) ON DELETE RESTRICT
);

-- PAY-08: 禮金名冊主檔
CREATE TABLE IF NOT EXISTS pay_gift_roster (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campaign_id     BIGINT NOT NULL,
    roster_no       VARCHAR(50)     NOT NULL,
    roster_type     VARCHAR(30)     NOT NULL DEFAULT 'distribution',
    total_count     INT             NOT NULL DEFAULT 0,
    total_amount    DECIMAL(14)  NOT NULL DEFAULT 0,
    roster_status   VARCHAR(30)     NOT NULL DEFAULT 'draft',
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (roster_no),
    INDEX idx_campaign_id (campaign_id),
    CONSTRAINT fk_roster_campaign FOREIGN KEY (campaign_id) REFERENCES pay_gift_campaign(id) ON DELETE RESTRICT
);

-- PAY-09: 禮金名冊明細
CREATE TABLE IF NOT EXISTS pay_gift_roster_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    roster_id       BIGINT NOT NULL,
    employee_id     BIGINT DEFAULT NULL,
    recipient_name  VARCHAR(100)    NOT NULL,
    amount          DECIMAL(12)  NOT NULL,
    is_received     BOOLEAN      NOT NULL DEFAULT 0,
    received_at     TIMESTAMP(6)     DEFAULT NULL,
    remark          VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_roster_id (roster_id),
    INDEX idx_employee_id (employee_id),
    CONSTRAINT fk_roster_item_roster FOREIGN KEY (roster_id) REFERENCES pay_gift_roster(id) ON DELETE RESTRICT
);

-- PAY-10: 禮金結算
CREATE TABLE IF NOT EXISTS pay_gift_settlement (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campaign_id     BIGINT NOT NULL,
    actual_count    INT             NOT NULL,
    actual_amount   DECIMAL(14)  NOT NULL,
    unclaimed_count INT             NOT NULL DEFAULT 0,
    unclaimed_amount DECIMAL(14) NOT NULL DEFAULT 0,
    excess_amount   DECIMAL(14)  NOT NULL DEFAULT 0,
    difference_amount DECIMAL(14) NOT NULL DEFAULT 0,
    settlement_status VARCHAR(30)   NOT NULL DEFAULT 'draft',
    settled_by      BIGINT DEFAULT NULL,
    settled_at      TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (campaign_id),
    CONSTRAINT fk_settlement_campaign FOREIGN KEY (campaign_id) REFERENCES pay_gift_campaign(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 4. 領款確認與異議
-- ============================================================================

-- PAY-11: 領款確認
CREATE TABLE IF NOT EXISTS pay_receipt_confirmation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    disbursement_id BIGINT DEFAULT NULL,
    roster_item_id  BIGINT DEFAULT NULL,
    application_id  BIGINT DEFAULT NULL,
    confirm_type    VARCHAR(30)     NOT NULL,
    confirm_status  VARCHAR(30)     NOT NULL DEFAULT 'pending',
    recipient_name  VARCHAR(100)    NOT NULL,
    confirmed_by    BIGINT DEFAULT NULL,
    confirmed_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_disbursement_id (disbursement_id),
    INDEX idx_roster_item_id (roster_item_id),
    INDEX idx_application_id (application_id),
    CONSTRAINT fk_receipt_disbursement FOREIGN KEY (disbursement_id) REFERENCES pay_disbursement(id) ON DELETE SET NULL,
    CONSTRAINT fk_receipt_roster_item FOREIGN KEY (roster_item_id) REFERENCES pay_gift_roster_item(id) ON DELETE SET NULL
);

-- PAY-12: 撥款異議
CREATE TABLE IF NOT EXISTS pay_dispute (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    disbursement_id BIGINT DEFAULT NULL,
    application_id  BIGINT DEFAULT NULL,
    dispute_type    VARCHAR(30)     NOT NULL,
    dispute_amount  DECIMAL(12)  DEFAULT NULL,
    description     TEXT            NOT NULL,
    evidence_file_id BIGINT DEFAULT NULL,
    dispute_status  VARCHAR(30)     NOT NULL DEFAULT 'open',
    resolution      TEXT            DEFAULT NULL,
    resolved_by     BIGINT DEFAULT NULL,
    resolved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_disbursement_id (disbursement_id),
    INDEX idx_application_id (application_id),
    INDEX idx_dispute_status (dispute_status),
    CONSTRAINT fk_dispute_disbursement FOREIGN KEY (disbursement_id) REFERENCES pay_disbursement(id) ON DELETE SET NULL
);

-- PAY-13: 例外處理
CREATE TABLE IF NOT EXISTS pay_exception (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_id        BIGINT DEFAULT NULL,
    disbursement_id BIGINT DEFAULT NULL,
    exception_type  VARCHAR(30)     NOT NULL,
    exception_status VARCHAR(30)    NOT NULL DEFAULT 'open',
    description     TEXT            NOT NULL,
    resolution      TEXT            DEFAULT NULL,
    resolved_by     BIGINT DEFAULT NULL,
    resolved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_batch_id (batch_id),
    INDEX idx_disbursement_id (disbursement_id),
    INDEX idx_exception_status (exception_status)
);
