-- ============================================================================
-- 台鐵職工福利平台 — FIN 財務文件模組
-- 模組：12_finance.sql
-- 說明：會計科目、文件模板與版本、報銷單、核定名冊、傳票、分錄、來源關係、
--       文件版本歷史、文件輸出、對賬任務與差異
-- 依賴：01_sys.sql、02_file.sql、11_payment.sql
-- 設計原則：所有金額使用 DECIMAL、初稿／校對稿／終稿不覆蓋、最終財務文件不可修改
-- ============================================================================

-- schema via search_path

-- ============================================================================
-- 1. 會計基礎與模板
-- ============================================================================

-- FIN-01: 會計科目
CREATE TABLE IF NOT EXISTS fin_accounting_subject (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subject_code    VARCHAR(50)     NOT NULL,
    subject_name    VARCHAR(100)    NOT NULL,
    subject_type    VARCHAR(30)     NOT NULL,
    parent_id       BIGINT DEFAULT NULL,
    level           INT             NOT NULL DEFAULT 1,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (subject_code),
    INDEX idx_parent_id (parent_id),
    CONSTRAINT fk_subject_parent FOREIGN KEY (parent_id) REFERENCES fin_accounting_subject(id) ON DELETE SET NULL
);

-- FIN-02: 財務文件模板
CREATE TABLE IF NOT EXISTS fin_document_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_code   VARCHAR(50)     NOT NULL,
    template_name   VARCHAR(100)    NOT NULL,
    document_type   VARCHAR(30)     NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_code)
);

-- FIN-03: 模板版本
CREATE TABLE IF NOT EXISTS fin_document_template_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_id     BIGINT NOT NULL,
    version_no      INT             NOT NULL,
    render_rule_json JSONB           DEFAULT NULL,
    is_published    BOOLEAN      NOT NULL DEFAULT 0,
    published_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_id, version_no),
    CONSTRAINT fk_fin_template_version_template FOREIGN KEY (template_id) REFERENCES fin_document_template(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 2. 報銷單與核定名冊
-- ============================================================================

-- FIN-04: 報銷單主檔
CREATE TABLE IF NOT EXISTS fin_reimbursement_claim (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    claim_no        VARCHAR(50)     NOT NULL,
    batch_id        BIGINT DEFAULT NULL,
    template_version_id BIGINT DEFAULT NULL,
    org_unit_id     BIGINT DEFAULT NULL,
    total_amount    DECIMAL(14)  NOT NULL DEFAULT 0,
    currency_code   VARCHAR(3)      NOT NULL DEFAULT 'TWD',
    claim_status    VARCHAR(30)     NOT NULL DEFAULT 'draft',
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (claim_no),
    INDEX idx_batch_id (batch_id),
    INDEX idx_claim_status (claim_status),
    CONSTRAINT fk_claim_batch FOREIGN KEY (batch_id) REFERENCES pay_batch(id) ON DELETE SET NULL
);

-- FIN-05: 報銷單明細
CREATE TABLE IF NOT EXISTS fin_reimbursement_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    claim_id        BIGINT NOT NULL,
    application_id  BIGINT DEFAULT NULL,
    batch_item_id   BIGINT DEFAULT NULL,
    amount          DECIMAL(12)  NOT NULL,
    description     VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_claim_id (claim_id),
    INDEX idx_application_id (application_id),
    INDEX idx_batch_item_id (batch_item_id),
    CONSTRAINT fk_reimb_item_claim FOREIGN KEY (claim_id) REFERENCES fin_reimbursement_claim(id) ON DELETE RESTRICT
);

-- FIN-06: 核定名冊主檔
CREATE TABLE IF NOT EXISTS fin_approval_roster (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    roster_no       VARCHAR(50)     NOT NULL,
    source_batch_id BIGINT DEFAULT NULL,
    template_version_id BIGINT DEFAULT NULL,
    total_count     INT             NOT NULL DEFAULT 0,
    total_amount    DECIMAL(14)  NOT NULL DEFAULT 0,
    currency_code   VARCHAR(3)      NOT NULL DEFAULT 'TWD',
    roster_status   VARCHAR(30)     NOT NULL DEFAULT 'draft',
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (roster_no),
    INDEX idx_source_batch_id (source_batch_id),
    CONSTRAINT fk_roster_batch FOREIGN KEY (source_batch_id) REFERENCES pay_batch(id) ON DELETE SET NULL
);

-- FIN-07: 核定名冊明細
CREATE TABLE IF NOT EXISTS fin_approval_roster_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    roster_id       BIGINT NOT NULL,
    application_id  BIGINT DEFAULT NULL,
    employee_no     VARCHAR(20)     NOT NULL,
    employee_name   VARCHAR(100)    NOT NULL,
    benefit_type_name VARCHAR(100)  NOT NULL,
    amount          DECIMAL(12)  NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_roster_id (roster_id),
    INDEX idx_application_id (application_id),
    CONSTRAINT fk_approval_roster_item_roster FOREIGN KEY (roster_id) REFERENCES fin_approval_roster(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 3. 傳票
-- ============================================================================

-- FIN-08: 傳票主檔
CREATE TABLE IF NOT EXISTS fin_voucher (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    voucher_no      VARCHAR(50)     NOT NULL,
    voucher_type    VARCHAR(30)     NOT NULL,
    voucher_date    DATE            NOT NULL,
    template_version_id BIGINT DEFAULT NULL,
    total_debit     DECIMAL(14)  NOT NULL DEFAULT 0,
    total_credit    DECIMAL(14)  NOT NULL DEFAULT 0,
    currency_code   VARCHAR(3)      NOT NULL DEFAULT 'TWD',
    voucher_status  VARCHAR(30)     NOT NULL DEFAULT 'draft',
    description     VARCHAR(500)    DEFAULT NULL,
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (voucher_no),
    INDEX idx_voucher_type (voucher_type),
    INDEX idx_voucher_date (voucher_date),
    INDEX idx_voucher_status (voucher_status)
);

-- FIN-09: 傳票分錄
CREATE TABLE IF NOT EXISTS fin_voucher_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    voucher_id      BIGINT NOT NULL,
    line_order      INT             NOT NULL,
    direction       VARCHAR(10)     NOT NULL,
    subject_id      BIGINT NOT NULL,
    amount          DECIMAL(14)  NOT NULL,
    summary         VARCHAR(200)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_voucher_id (voucher_id),
    INDEX idx_subject_id (subject_id),
    CONSTRAINT fk_voucher_line_voucher FOREIGN KEY (voucher_id) REFERENCES fin_voucher(id) ON DELETE RESTRICT,
    CONSTRAINT fk_voucher_line_subject FOREIGN KEY (subject_id) REFERENCES fin_accounting_subject(id) ON DELETE RESTRICT
);

-- FIN-10: 傳票來源關係
CREATE TABLE IF NOT EXISTS fin_voucher_source_link (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    voucher_id      BIGINT NOT NULL,
    source_type     VARCHAR(30)     NOT NULL,
    source_id       BIGINT NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_voucher_id (voucher_id),
    INDEX idx_source (source_type, source_id),
    CONSTRAINT fk_voucher_source_voucher FOREIGN KEY (voucher_id) REFERENCES fin_voucher(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 4. 文件版本與輸出
-- ============================================================================

-- FIN-11: 文件版本歷史
CREATE TABLE IF NOT EXISTS fin_document_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_type   VARCHAR(30)     NOT NULL,
    document_id     BIGINT NOT NULL,
    version_no      INT             NOT NULL,
    version_label   VARCHAR(30)     NOT NULL,
    content_json    JSONB            DEFAULT NULL,
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (document_type, document_id, version_no),
    INDEX idx_document (document_type, document_id),
    CONSTRAINT fk_doc_version_voucher FOREIGN KEY (document_id) REFERENCES fin_voucher(id) ON DELETE RESTRICT
);

-- FIN-12: 文件輸出
CREATE TABLE IF NOT EXISTS fin_document_output (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_version_id BIGINT NOT NULL,
    file_id         BIGINT NOT NULL,
    output_format   VARCHAR(30)     NOT NULL,
    is_final        BOOLEAN      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_document_version_id (document_version_id),
    INDEX idx_file_id (file_id),
    CONSTRAINT fk_output_version FOREIGN KEY (document_version_id) REFERENCES fin_document_version(id) ON DELETE RESTRICT,
    CONSTRAINT fk_output_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 5. 對賬
-- ============================================================================

-- FIN-13: 對賬任務
CREATE TABLE IF NOT EXISTS fin_reconciliation_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    run_no          VARCHAR(50)     NOT NULL,
    reconciliation_type VARCHAR(30) NOT NULL,
    source_batch_id BIGINT DEFAULT NULL,
    start_date      DATE            DEFAULT NULL,
    end_date        DATE            DEFAULT NULL,
    run_status      VARCHAR(30)     NOT NULL DEFAULT 'pending',
    total_checked   INT             NOT NULL DEFAULT 0,
    difference_count INT            NOT NULL DEFAULT 0,
    run_by          BIGINT DEFAULT NULL,
    started_at      TIMESTAMP(6)     DEFAULT NULL,
    finished_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (run_no),
    INDEX idx_source_batch_id (source_batch_id),
    INDEX idx_run_status (run_status)
);

-- FIN-14: 對賬差異
CREATE TABLE IF NOT EXISTS fin_reconciliation_difference (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reconciliation_run_id BIGINT NOT NULL,
    object_type     VARCHAR(30)     NOT NULL,
    object_id       BIGINT NOT NULL,
    field_name      VARCHAR(50)     NOT NULL,
    expected_value  VARCHAR(255)    NOT NULL,
    actual_value    VARCHAR(255)    NOT NULL,
    difference_type VARCHAR(30)     NOT NULL DEFAULT 'amount',
    severity        VARCHAR(30)     NOT NULL DEFAULT 'medium',
    resolution_status VARCHAR(30)   NOT NULL DEFAULT 'unresolved',
    resolution      TEXT            DEFAULT NULL,
    resolved_by     BIGINT DEFAULT NULL,
    resolved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_reconciliation_run_id (reconciliation_run_id),
    INDEX idx_resolution_status (resolution_status),
    CONSTRAINT fk_recon_diff_run FOREIGN KEY (reconciliation_run_id) REFERENCES fin_reconciliation_run(id) ON DELETE RESTRICT
);
