-- ============================================================================
-- 台鐵職工福利平台 — AI OCR 與異常預警模組
-- 模組：13_ai_ocr.sql
-- 說明：模型註冊、OCR 任務與嘗試、影像品質、辨識結果與欄位、人工修正、
--       異常規則與結果、重複特徵與比對、處理軌跡
-- 依賴：01_sys.sql、02_file.sql、09_ben_application.sql
-- 設計原則：OCR 僅輔助判斷、不具最終核定效力、人工修正不覆蓋原始結果
-- ============================================================================

-- schema via search_path

-- AI-01: 模型註冊
CREATE TABLE IF NOT EXISTS ai_model_registry (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_code      VARCHAR(50)     NOT NULL,
    model_name      VARCHAR(100)    NOT NULL,
    model_version   VARCHAR(30)     NOT NULL,
    model_type      VARCHAR(30)     NOT NULL,
    provider        VARCHAR(50)     DEFAULT NULL,
    config_json     JSONB            DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (model_code)
);

-- AI-02: OCR 任務
CREATE TABLE IF NOT EXISTS ai_ocr_job (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_id         BIGINT NOT NULL,
    application_id  BIGINT DEFAULT NULL,
    model_id        BIGINT NOT NULL,
    job_status      VARCHAR(30)     NOT NULL DEFAULT 'pending',
    priority        INT             NOT NULL DEFAULT 5,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_file_id (file_id),
    INDEX idx_application_id (application_id),
    INDEX idx_job_status (job_status),
    INDEX idx_priority (priority),
    CONSTRAINT fk_ocr_job_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ocr_job_model FOREIGN KEY (model_id) REFERENCES ai_model_registry(id) ON DELETE RESTRICT
);

-- AI-03: OCR 嘗試
CREATE TABLE IF NOT EXISTS ai_ocr_attempt (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ocr_job_id      BIGINT NOT NULL,
    attempt_no      INT             NOT NULL,
    attempt_status  VARCHAR(30)     NOT NULL DEFAULT 'processing',
    duration_ms     INT             DEFAULT NULL,
    error_message   TEXT            DEFAULT NULL,
    processing_node VARCHAR(100)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_ocr_job_id (ocr_job_id),
    CONSTRAINT fk_ocr_attempt_job FOREIGN KEY (ocr_job_id) REFERENCES ai_ocr_job(id) ON DELETE RESTRICT
);

-- AI-04: 文件品質結果
CREATE TABLE IF NOT EXISTS ai_document_quality_result (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_id         BIGINT NOT NULL,
    ocr_job_id      BIGINT DEFAULT NULL,
    quality_status  VARCHAR(30)     NOT NULL,
    confidence_score DECIMAL(5, 2)  DEFAULT NULL,
    details_json    JSONB            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_file_id (file_id),
    INDEX idx_quality_status (quality_status),
    CONSTRAINT fk_quality_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- AI-05: OCR 結果
CREATE TABLE IF NOT EXISTS ai_ocr_result (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ocr_attempt_id  BIGINT NOT NULL,
    model_id        BIGINT NOT NULL,
    raw_result_json JSONB            NOT NULL,
    overall_confidence DECIMAL(5, 2) DEFAULT NULL,
    processed_at    TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_ocr_attempt_id (ocr_attempt_id),
    CONSTRAINT fk_ocr_result_attempt FOREIGN KEY (ocr_attempt_id) REFERENCES ai_ocr_attempt(id) ON DELETE RESTRICT
);

-- AI-06: OCR 欄位
CREATE TABLE IF NOT EXISTS ai_ocr_field (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ocr_result_id   BIGINT NOT NULL,
    field_name      VARCHAR(100)    NOT NULL,
    field_value     TEXT            NOT NULL,
    confidence      DECIMAL(5, 2)   DEFAULT NULL,
    bounding_box_json JSONB          DEFAULT NULL,
    field_type      VARCHAR(30)     DEFAULT NULL,
    is_normalized   BOOLEAN      NOT NULL DEFAULT 0,
    normalized_value TEXT           DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_ocr_result_id (ocr_result_id),
    INDEX idx_field_name (field_name),
    CONSTRAINT fk_ocr_field_result FOREIGN KEY (ocr_result_id) REFERENCES ai_ocr_result(id) ON DELETE RESTRICT
);

-- AI-07: 人工修正
CREATE TABLE IF NOT EXISTS ai_manual_correction (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ocr_field_id    BIGINT NOT NULL,
    original_value  TEXT            NOT NULL,
    corrected_value TEXT            NOT NULL,
    corrected_by    BIGINT DEFAULT NULL,
    correction_reason VARCHAR(500)  DEFAULT NULL,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_ocr_field_id (ocr_field_id),
    INDEX idx_corrected_by (corrected_by),
    CONSTRAINT fk_correction_field FOREIGN KEY (ocr_field_id) REFERENCES ai_ocr_field(id) ON DELETE RESTRICT
);

-- AI-08: 異常規則
CREATE TABLE IF NOT EXISTS ai_anomaly_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rule_code       VARCHAR(50)     NOT NULL,
    rule_name       VARCHAR(100)    NOT NULL,
    rule_type       VARCHAR(30)     NOT NULL,
    severity        VARCHAR(30)     NOT NULL DEFAULT 'medium',
    condition_json  JSONB            NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    version_no      INT             NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (rule_code)
);

-- AI-09: 異常結果
CREATE TABLE IF NOT EXISTS ai_anomaly_result (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT DEFAULT NULL,
    rule_id         BIGINT NOT NULL,
    severity        VARCHAR(30)     NOT NULL,
    evidence_json   JSONB            NOT NULL,
    result_status   VARCHAR(30)     NOT NULL DEFAULT 'open',
    handled_by      BIGINT DEFAULT NULL,
    handled_at      TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_application_id (application_id),
    INDEX idx_rule_id (rule_id),
    INDEX idx_result_status (result_status),
    CONSTRAINT fk_anomaly_application FOREIGN KEY (application_id) REFERENCES ben_application(id) ON DELETE SET NULL,
    CONSTRAINT fk_anomaly_rule FOREIGN KEY (rule_id) REFERENCES ai_anomaly_rule(id) ON DELETE RESTRICT
);

-- AI-10: 重複特徵摘要
CREATE TABLE IF NOT EXISTS ai_duplicate_fingerprint (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fingerprint_hash VARCHAR(64)    NOT NULL,
    fingerprint_type VARCHAR(30)    NOT NULL,
    source_object_type VARCHAR(50)  DEFAULT NULL,
    source_object_id BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_fingerprint_hash (fingerprint_hash),
    INDEX idx_fingerprint_type (fingerprint_type)
);

-- AI-11: 重複比對結果
CREATE TABLE IF NOT EXISTS ai_duplicate_match (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_application_id BIGINT NOT NULL,
    candidate_application_id BIGINT NOT NULL,
    match_score     DECIMAL(5, 2)   NOT NULL,
    match_type      VARCHAR(30)     NOT NULL,
    evidence_json   JSONB            DEFAULT NULL,
    human_decision  VARCHAR(30)     DEFAULT NULL,
    decided_by      BIGINT DEFAULT NULL,
    decided_at      TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_source_application (source_application_id),
    INDEX idx_candidate_application (candidate_application_id),
    INDEX idx_match_score (match_score),
    CONSTRAINT fk_match_source FOREIGN KEY (source_application_id) REFERENCES ben_application(id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_candidate FOREIGN KEY (candidate_application_id) REFERENCES ben_application(id) ON DELETE RESTRICT
);

-- AI-12: 處理軌跡
CREATE TABLE IF NOT EXISTS ai_processing_trace (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ocr_job_id      BIGINT DEFAULT NULL,
    trace_stage     VARCHAR(30)     NOT NULL,
    trace_detail    TEXT            DEFAULT NULL,
    processing_node VARCHAR(100)    DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_ocr_job_id (ocr_job_id),
    INDEX idx_trace_stage (trace_stage)
);
