-- ============================================================================
-- 台鐵職工福利平台 — MCH 特約商店模組
-- 模組：14_merchant.sql
-- 說明：商店分類、主檔、分店、聯絡人、合約、合約文件、優惠、優惠媒體、
--       變更申請與工作流橋接、狀態歷史、到期提醒、推播偏好、地理圍欄事件、冷卻
-- 依賴：01_sys.sql、02_file.sql、10_workflow.sql
-- ============================================================================

-- schema via search_path

-- MCH-01: 商店分類
CREATE TABLE IF NOT EXISTS mch_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category_code   VARCHAR(30)     NOT NULL,
    category_name   VARCHAR(100)    NOT NULL,
    parent_id       BIGINT DEFAULT NULL,
    sort_order      INT             NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (category_code),
    INDEX idx_parent_id (parent_id)
);

-- MCH-02: 商店主檔
CREATE TABLE IF NOT EXISTS mch_merchant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_code   VARCHAR(50)     NOT NULL,
    merchant_name   VARCHAR(200)    NOT NULL,
    unified_business_no VARCHAR(20) DEFAULT NULL,
    merchant_status VARCHAR(30)     NOT NULL DEFAULT 'active',
    category_id     BIGINT DEFAULT NULL,
    description     TEXT            DEFAULT NULL,
    phone           VARCHAR(30)     DEFAULT NULL,
    website         VARCHAR(500)    DEFAULT NULL,
    is_published    BOOLEAN      NOT NULL DEFAULT 0,
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (merchant_code),
    INDEX idx_unified_business_no (unified_business_no),
    INDEX idx_merchant_status (merchant_status),
    INDEX idx_category_id (category_id),
    INDEX idx_is_published (is_published)
);

-- MCH-03: 分店
CREATE TABLE IF NOT EXISTS mch_branch (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id     BIGINT NOT NULL,
    branch_name     VARCHAR(200)    NOT NULL,
    address         VARCHAR(500)    DEFAULT NULL,
    latitude        DECIMAL(10, 7)  DEFAULT NULL,
    longitude       DECIMAL(10, 7)  DEFAULT NULL,
    phone           VARCHAR(30)     DEFAULT NULL,
    business_hours  VARCHAR(200)    DEFAULT NULL,
    branch_status   VARCHAR(30)     NOT NULL DEFAULT 'active',
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_merchant_id (merchant_id),
    INDEX idx_branch_status (branch_status),
    INDEX idx_location (latitude, longitude),
    CONSTRAINT fk_branch_merchant FOREIGN KEY (merchant_id) REFERENCES mch_merchant(id) ON DELETE RESTRICT
);

-- MCH-04: 內部聯絡窗口
CREATE TABLE IF NOT EXISTS mch_contact (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id     BIGINT NOT NULL,
    contact_name    VARCHAR(100)    NOT NULL,
    phone           VARCHAR(30)     DEFAULT NULL,
    email           VARCHAR(200)    DEFAULT NULL,
    position        VARCHAR(100)    DEFAULT NULL,
    is_primary      BOOLEAN      NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_merchant_id (merchant_id),
    CONSTRAINT fk_contact_merchant FOREIGN KEY (merchant_id) REFERENCES mch_merchant(id) ON DELETE RESTRICT
);

-- MCH-05: 合約
CREATE TABLE IF NOT EXISTS mch_contract (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id     BIGINT NOT NULL,
    contract_no     VARCHAR(50)     NOT NULL,
    contract_name   VARCHAR(200)    NOT NULL,
    contract_type   VARCHAR(30)     NOT NULL DEFAULT 'cooperation',
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    contract_status VARCHAR(30)     NOT NULL DEFAULT 'draft',
    internal_note   TEXT            DEFAULT NULL,
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (contract_no),
    INDEX idx_merchant_id (merchant_id),
    INDEX idx_contract_status (contract_status),
    INDEX idx_effective_date (effective_date, expiration_date),
    CONSTRAINT fk_contract_merchant FOREIGN KEY (merchant_id) REFERENCES mch_merchant(id) ON DELETE RESTRICT
);

-- MCH-06: 合約文件
CREATE TABLE IF NOT EXISTS mch_contract_document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    contract_id     BIGINT NOT NULL,
    file_id         BIGINT NOT NULL,
    document_type   VARCHAR(30)     NOT NULL,
    version_no      INT             NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_contract_id (contract_id),
    INDEX idx_file_id (file_id),
    CONSTRAINT fk_contract_doc_contract FOREIGN KEY (contract_id) REFERENCES mch_contract(id) ON DELETE RESTRICT,
    CONSTRAINT fk_contract_doc_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- MCH-07: 優惠內容
CREATE TABLE IF NOT EXISTS mch_offer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id     BIGINT NOT NULL,
    branch_id       BIGINT DEFAULT NULL,
    offer_title     VARCHAR(200)    NOT NULL,
    offer_type      VARCHAR(30)     NOT NULL DEFAULT 'discount',
    terms_json      JSONB            DEFAULT NULL,
    effective_date  DATE            NOT NULL,
    expiration_date DATE            DEFAULT NULL,
    publish_status  VARCHAR(30)     NOT NULL DEFAULT 'draft',
    is_featured     BOOLEAN      NOT NULL DEFAULT 0,
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_merchant_id (merchant_id),
    INDEX idx_branch_id (branch_id),
    INDEX idx_publish_status (publish_status, effective_date, expiration_date),
    CONSTRAINT fk_offer_merchant FOREIGN KEY (merchant_id) REFERENCES mch_merchant(id) ON DELETE RESTRICT,
    CONSTRAINT fk_offer_branch FOREIGN KEY (branch_id) REFERENCES mch_branch(id) ON DELETE SET NULL
);

-- MCH-08: 優惠媒體
CREATE TABLE IF NOT EXISTS mch_offer_media (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    offer_id        BIGINT NOT NULL,
    file_id         BIGINT NOT NULL,
    media_type      VARCHAR(30)     NOT NULL,
    sort_order      INT             NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_offer_id (offer_id),
    INDEX idx_file_id (file_id),
    CONSTRAINT fk_offer_media_offer FOREIGN KEY (offer_id) REFERENCES mch_offer(id) ON DELETE RESTRICT,
    CONSTRAINT fk_offer_media_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- MCH-09: 商店異動申請
CREATE TABLE IF NOT EXISTS mch_change_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id     BIGINT NOT NULL,
    change_type     VARCHAR(30)     NOT NULL,
    proposed_json   JSONB            NOT NULL,
    reason          TEXT            NOT NULL,
    request_status  VARCHAR(30)     NOT NULL DEFAULT 'draft',
    requested_by    BIGINT NOT NULL,
    approved_by     BIGINT DEFAULT NULL,
    approved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_merchant_id (merchant_id),
    INDEX idx_request_status (request_status)
);

-- MCH-10: 商店異動-工作流橋接
CREATE TABLE IF NOT EXISTS mch_change_workflow (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    change_request_id BIGINT NOT NULL,
    wf_instance_id  BIGINT NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (change_request_id, wf_instance_id),
    INDEX idx_wf_instance_id (wf_instance_id),
    CONSTRAINT fk_mch_change_wf_request FOREIGN KEY (change_request_id) REFERENCES mch_change_request(id) ON DELETE RESTRICT,
    CONSTRAINT fk_mch_change_wf_instance FOREIGN KEY (wf_instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT
);

-- MCH-11: 狀態歷史
CREATE TABLE IF NOT EXISTS mch_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id     BIGINT NOT NULL,
    from_status     VARCHAR(30)     DEFAULT NULL,
    to_status       VARCHAR(30)     NOT NULL,
    change_reason   VARCHAR(500)    DEFAULT NULL,
    changed_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_merchant_id (merchant_id),
    CONSTRAINT fk_mch_status_merchant FOREIGN KEY (merchant_id) REFERENCES mch_merchant(id) ON DELETE RESTRICT
);

-- MCH-12: 到期提醒記錄
CREATE TABLE IF NOT EXISTS mch_expiry_reminder (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    contract_id     BIGINT DEFAULT NULL,
    offer_id        BIGINT DEFAULT NULL,
    reminder_type   VARCHAR(30)     NOT NULL,
    days_before     INT             NOT NULL,
    reminder_key    VARCHAR(64)     NOT NULL,
    is_sent         BOOLEAN      NOT NULL DEFAULT 0,
    sent_at         TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (reminder_key),
    INDEX idx_contract_id (contract_id),
    INDEX idx_is_sent (is_sent)
);

-- MCH-13: 使用者推播偏好
CREATE TABLE IF NOT EXISTS mch_user_push_preference (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    max_distance_km DECIMAL(6, 1)   DEFAULT NULL,
    min_push_interval_minutes INT   NOT NULL DEFAULT 60,
    preferred_categories_json JSONB  DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (account_id),
    CONSTRAINT fk_push_pref_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT
);

-- MCH-14: 地理圍欄事件
CREATE TABLE IF NOT EXISTS mch_geofence_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT DEFAULT NULL,
    branch_id       BIGINT NOT NULL,
    event_type      VARCHAR(30)     NOT NULL,
    latitude        DECIMAL(10, 7)  NOT NULL,
    longitude       DECIMAL(10, 7)  NOT NULL,
    accuracy_meters INT             DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_account_id (account_id),
    INDEX idx_branch_id (branch_id),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_geofence_branch FOREIGN KEY (branch_id) REFERENCES mch_branch(id) ON DELETE RESTRICT
);

-- MCH-15: 推播冷卻
CREATE TABLE IF NOT EXISTS mch_push_cooldown (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT NOT NULL,
    merchant_id     BIGINT NOT NULL,
    last_pushed_at  TIMESTAMP(6)     NOT NULL,
    cooldown_minutes INT            NOT NULL DEFAULT 60,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (account_id, merchant_id),
    CONSTRAINT fk_cooldown_account FOREIGN KEY (account_id) REFERENCES iam_account(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cooldown_merchant FOREIGN KEY (merchant_id) REFERENCES mch_merchant(id) ON DELETE RESTRICT
);
