-- ============================================================================
-- 台鐵職工福利平台 — ANN 公告發佈模組
-- 模組：15_announcement.sql
-- 說明：公告分類、主檔、內容版本、附件、分眾規則、排程、審批橋接、發佈記錄、
--       觸及統計、地理規則
-- 依賴：01_sys.sql、02_file.sql、05_iam.sql、10_workflow.sql
-- 設計原則：公告正文版本化、發佈時固化受眾快照、撤回不刪除歷史
-- ============================================================================

-- schema via search_path

-- ANN-01: 公告分類
CREATE TABLE IF NOT EXISTS ann_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category_code   VARCHAR(30)     NOT NULL,
    category_name   VARCHAR(100)    NOT NULL,
    sort_order      INT             NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (category_code)
);

-- ANN-02: 公告主檔
CREATE TABLE IF NOT EXISTS ann_announcement (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    announcement_no VARCHAR(50)     NOT NULL,
    title           VARCHAR(200)    NOT NULL,
    category_id     BIGINT DEFAULT NULL,
    priority        VARCHAR(10)     NOT NULL DEFAULT 'normal',
    announcement_status VARCHAR(30) NOT NULL DEFAULT 'draft',
    is_pinned       BOOLEAN      NOT NULL DEFAULT 0,
    is_all_employees BOOLEAN     NOT NULL DEFAULT 0,
    created_by      BIGINT DEFAULT NULL,
    published_by    BIGINT DEFAULT NULL,
    published_at    TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (announcement_no),
    INDEX idx_category_id (category_id),
    INDEX idx_announcement_status (announcement_status),
    INDEX idx_published_at (published_at),
    INDEX idx_is_pinned (is_pinned)
);

-- ANN-03: 公告內容版本
CREATE TABLE IF NOT EXISTS ann_content_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    announcement_id BIGINT NOT NULL,
    version_no      INT             NOT NULL,
    title           VARCHAR(200)    NOT NULL,
    body            TEXT            NOT NULL,
    content_format  VARCHAR(30)     NOT NULL DEFAULT 'html',
    change_summary  VARCHAR(500)    DEFAULT NULL,
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (announcement_id, version_no),
    CONSTRAINT fk_ann_content_announcement FOREIGN KEY (announcement_id) REFERENCES ann_announcement(id) ON DELETE RESTRICT
);

-- ANN-04: 公告附件
CREATE TABLE IF NOT EXISTS ann_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    announcement_id BIGINT NOT NULL,
    file_id         BIGINT NOT NULL,
    sort_order      INT             NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_announcement_id (announcement_id),
    INDEX idx_file_id (file_id),
    CONSTRAINT fk_ann_attachment_announcement FOREIGN KEY (announcement_id) REFERENCES ann_announcement(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ann_attachment_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- ANN-05: 分眾規則
CREATE TABLE IF NOT EXISTS ann_audience_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    announcement_id BIGINT NOT NULL,
    criteria_json   JSONB            NOT NULL,
    version_no      INT             NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_announcement_id (announcement_id),
    CONSTRAINT fk_ann_audience_announcement FOREIGN KEY (announcement_id) REFERENCES ann_announcement(id) ON DELETE RESTRICT
);

-- ANN-06: 排程設定
CREATE TABLE IF NOT EXISTS ann_schedule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    announcement_id BIGINT NOT NULL,
    schedule_type   VARCHAR(30)     NOT NULL DEFAULT 'immediate',
    start_at        TIMESTAMP(6)     DEFAULT NULL,
    end_at          TIMESTAMP(6)     DEFAULT NULL,
    cron_expression VARCHAR(100)    DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (announcement_id),
    CONSTRAINT fk_ann_schedule_announcement FOREIGN KEY (announcement_id) REFERENCES ann_announcement(id) ON DELETE RESTRICT
);

-- ANN-07: 公告審批橋接
CREATE TABLE IF NOT EXISTS ann_publish_workflow (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    announcement_id BIGINT NOT NULL,
    wf_instance_id  BIGINT NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (announcement_id, wf_instance_id),
    INDEX idx_wf_instance_id (wf_instance_id),
    CONSTRAINT fk_ann_publish_wf_announcement FOREIGN KEY (announcement_id) REFERENCES ann_announcement(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ann_publish_wf_instance FOREIGN KEY (wf_instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT
);

-- ANN-08: 發佈記錄
CREATE TABLE IF NOT EXISTS ann_publish_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    announcement_id BIGINT NOT NULL,
    record_type     VARCHAR(30)     NOT NULL,
    content_version_id BIGINT DEFAULT NULL,
    audience_snapshot_json JSONB    DEFAULT NULL,
    operated_by     BIGINT DEFAULT NULL,
    operated_at     TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_announcement_id (announcement_id),
    CONSTRAINT fk_ann_publish_record_announcement FOREIGN KEY (announcement_id) REFERENCES ann_announcement(id) ON DELETE RESTRICT
);

-- ANN-09: 觸及統計摘要
CREATE TABLE IF NOT EXISTS ann_reach_summary (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    announcement_id BIGINT NOT NULL,
    total_recipients INT            NOT NULL DEFAULT 0,
    delivered_count INT             NOT NULL DEFAULT 0,
    read_count      INT             NOT NULL DEFAULT 0,
    channel_json    JSONB            DEFAULT NULL,
    summary_date    DATE            NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (announcement_id, summary_date),
    CONSTRAINT fk_ann_reach_announcement FOREIGN KEY (announcement_id) REFERENCES ann_announcement(id) ON DELETE RESTRICT
);

-- ANN-10: 地理圍欄規則
CREATE TABLE IF NOT EXISTS ann_location_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    announcement_id BIGINT NOT NULL,
    latitude        DECIMAL(10, 7)  NOT NULL,
    longitude       DECIMAL(10, 7)  NOT NULL,
    radius_meters   INT             NOT NULL,
    trigger_event   VARCHAR(30)     NOT NULL DEFAULT 'enter',
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_announcement_id (announcement_id),
    CONSTRAINT fk_ann_location_announcement FOREIGN KEY (announcement_id) REFERENCES ann_announcement(id) ON DELETE RESTRICT
);
