-- ============================================================================
-- 台鐵職工福利平台 — SEC 稽核與資安模組
-- 模組：16_security_audit.sql
-- 說明：全域審計事件、變更差異、哈希鏈檢查點、資料存取事件、冷歸檔、
--       安全告警與處置、掃描規則與任務、發現結果、合規文件、日誌匯出
-- 依賴：01_sys.sql、02_file.sql、05_iam.sql
-- 設計原則：審計日誌僅可追加、業務帳號不得更新或刪除、敏感值脫敏
-- ============================================================================

-- schema via search_path

-- ============================================================================
-- 1. 審計核心
-- ============================================================================

-- SEC-01: 全域審計事件
CREATE TABLE IF NOT EXISTS sec_audit_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_time      TIMESTAMP(6)     NOT NULL,
    module_code     VARCHAR(30)     NOT NULL,
    action_code     VARCHAR(50)     NOT NULL,
    actor_account_id BIGINT DEFAULT NULL,
    actor_name      VARCHAR(100)    DEFAULT NULL,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    request_trace   VARCHAR(64)     DEFAULT NULL,
    object_type     VARCHAR(50)     DEFAULT NULL,
    object_id       BIGINT DEFAULT NULL,
    object_identifier VARCHAR(200)  DEFAULT NULL,
    result_status   VARCHAR(30)     NOT NULL,
    detail          TEXT            DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_event_time (event_time),
    INDEX idx_module_action (module_code, action_code),
    INDEX idx_actor (actor_account_id, event_time),
    INDEX idx_object (object_type, object_id, event_time),
    INDEX idx_request_trace (request_trace)
);

-- SEC-02: 審計變更差異
CREATE TABLE IF NOT EXISTS sec_audit_change (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    audit_event_id  BIGINT NOT NULL,
    before_json     JSONB            DEFAULT NULL,
    after_json      JSONB            NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_audit_event_id (audit_event_id),
    CONSTRAINT fk_audit_change_event FOREIGN KEY (audit_event_id) REFERENCES sec_audit_event(id) ON DELETE RESTRICT
);

-- SEC-03: 審計哈希鏈檢查點
CREATE TABLE IF NOT EXISTS sec_audit_chain_checkpoint (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    checkpoint_time TIMESTAMP(6)     NOT NULL,
    last_event_id   BIGINT NOT NULL,
    chain_hash      VARCHAR(64)     NOT NULL,
    checkpoint_type VARCHAR(30)     NOT NULL DEFAULT 'periodic',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (checkpoint_time, checkpoint_type)
);

-- SEC-04: 資料存取事件
CREATE TABLE IF NOT EXISTS sec_data_access_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_time      TIMESTAMP(6)     NOT NULL,
    actor_account_id BIGINT DEFAULT NULL,
    access_type     VARCHAR(30)     NOT NULL,
    data_category   VARCHAR(50)     NOT NULL,
    object_type     VARCHAR(50)     DEFAULT NULL,
    object_id       BIGINT DEFAULT NULL,
    filter_summary  VARCHAR(500)    DEFAULT NULL,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    request_trace   VARCHAR(64)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_event_time (event_time),
    INDEX idx_actor (actor_account_id, event_time),
    INDEX idx_access_type (access_type),
    INDEX idx_data_category (data_category)
);

-- ============================================================================
-- 2. 冷歸檔
-- ============================================================================

-- SEC-05: 審計冷歸檔
CREATE TABLE IF NOT EXISTS sec_audit_archive (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    archive_batch_no VARCHAR(50)    NOT NULL,
    archive_date    DATE            NOT NULL,
    start_event_id  BIGINT NOT NULL,
    end_event_id    BIGINT NOT NULL,
    total_events    INT             NOT NULL DEFAULT 0,
    archive_file_key VARCHAR(128)   DEFAULT NULL,
    archive_checksum VARCHAR(64)    DEFAULT NULL,
    digital_signature VARCHAR(256)  DEFAULT NULL,
    archive_status  VARCHAR(30)     NOT NULL DEFAULT 'pending',
    archived_by     BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (archive_batch_no),
    INDEX idx_archive_date (archive_date)
);

-- ============================================================================
-- 3. 安全告警
-- ============================================================================

-- SEC-06: 安全告警
CREATE TABLE IF NOT EXISTS sec_security_alert (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    alert_type      VARCHAR(50)     NOT NULL,
    alert_severity  VARCHAR(30)     NOT NULL DEFAULT 'medium',
    alert_title     VARCHAR(200)    NOT NULL,
    alert_detail    TEXT            DEFAULT NULL,
    source_ip       VARCHAR(45)     DEFAULT NULL,
    affected_account_id BIGINT DEFAULT NULL,
    alert_status    VARCHAR(30)     NOT NULL DEFAULT 'open',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_alert_type (alert_type),
    INDEX idx_alert_severity (alert_severity),
    INDEX idx_alert_status (alert_status),
    INDEX idx_created_at (created_at)
);

-- SEC-07: 告警處置動作
CREATE TABLE IF NOT EXISTS sec_alert_action (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    alert_id        BIGINT NOT NULL,
    action_type     VARCHAR(30)     NOT NULL,
    action_detail   TEXT            DEFAULT NULL,
    operator_id     BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_alert_id (alert_id),
    INDEX idx_action_type (action_type),
    CONSTRAINT fk_alert_action_alert FOREIGN KEY (alert_id) REFERENCES sec_security_alert(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 4. 安全掃描
-- ============================================================================

-- SEC-08: 掃描規則
CREATE TABLE IF NOT EXISTS sec_scan_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rule_code       VARCHAR(50)     NOT NULL,
    rule_name       VARCHAR(100)    NOT NULL,
    scan_type       VARCHAR(30)     NOT NULL,
    schedule_cron   VARCHAR(100)    DEFAULT NULL,
    config_json     JSONB            DEFAULT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT 1,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (rule_code)
);

-- SEC-09: 掃描任務
CREATE TABLE IF NOT EXISTS sec_scan_job (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    scan_rule_id    BIGINT NOT NULL,
    job_status      VARCHAR(30)     NOT NULL DEFAULT 'pending',
    total_findings  INT             NOT NULL DEFAULT 0,
    critical_count  INT             NOT NULL DEFAULT 0,
    high_count      INT             NOT NULL DEFAULT 0,
    medium_count    INT             NOT NULL DEFAULT 0,
    low_count       INT             NOT NULL DEFAULT 0,
    triggered_by    VARCHAR(30)     NOT NULL DEFAULT 'scheduler',
    started_at      TIMESTAMP(6)     DEFAULT NULL,
    finished_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_scan_rule_id (scan_rule_id),
    INDEX idx_job_status (job_status),
    CONSTRAINT fk_scan_job_rule FOREIGN KEY (scan_rule_id) REFERENCES sec_scan_rule(id) ON DELETE RESTRICT
);

-- SEC-10: 掃描發現
CREATE TABLE IF NOT EXISTS sec_scan_finding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    scan_job_id     BIGINT NOT NULL,
    finding_type    VARCHAR(50)     NOT NULL,
    severity        VARCHAR(30)     NOT NULL,
    title           VARCHAR(200)    NOT NULL,
    description     TEXT            DEFAULT NULL,
    affected_resource VARCHAR(500)  DEFAULT NULL,
    recommendation  TEXT            DEFAULT NULL,
    finding_status  VARCHAR(30)     NOT NULL DEFAULT 'open',
    resolved_at     TIMESTAMP(6)     DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_scan_job_id (scan_job_id),
    INDEX idx_severity (severity),
    INDEX idx_finding_status (finding_status),
    CONSTRAINT fk_scan_finding_job FOREIGN KEY (scan_job_id) REFERENCES sec_scan_job(id) ON DELETE RESTRICT
);

-- ============================================================================
-- 5. 合規與匯出
-- ============================================================================

-- SEC-11: 合規文件
CREATE TABLE IF NOT EXISTS sec_compliance_document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_type   VARCHAR(30)     NOT NULL,
    file_id         BIGINT NOT NULL,
    document_title  VARCHAR(200)    NOT NULL,
    document_date   DATE            DEFAULT NULL,
    is_confidential BOOLEAN      NOT NULL DEFAULT 1,
    created_by      BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_document_type (document_type),
    INDEX idx_file_id (file_id),
    CONSTRAINT fk_compliance_file FOREIGN KEY (file_id) REFERENCES file_object(id) ON DELETE RESTRICT
);

-- SEC-12: 日誌查詢匯出任務
CREATE TABLE IF NOT EXISTS sec_log_export_job (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_no      VARCHAR(50)     NOT NULL,
    export_scope_json JSONB          NOT NULL,
    export_reason   TEXT            NOT NULL,
    export_status   VARCHAR(30)     NOT NULL DEFAULT 'pending',
    result_file_id  BIGINT DEFAULT NULL,
    expires_at      TIMESTAMP(6)     DEFAULT NULL,
    requested_by    BIGINT NOT NULL,
    approved_by     BIGINT DEFAULT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (request_no),
    INDEX idx_export_status (export_status)
);
