#!/usr/bin/env python3
"""Convert MySQL DDL to PostgreSQL syntax. Reads mysql/modules/, writes postgresql/modules/."""

import os, re

BASE = "/Users/jeeshyang/MySpace/04_Employment/02_Part_Time/02_pencillink/TRA_PRD/sql"
SRC = os.path.join(BASE, "mysql/modules")
DST = os.path.join(BASE, "postgresql/modules")
os.makedirs(DST, exist_ok=True)


def convert_ddl(sql):
    sql = re.sub(r"^USE\s+\w+;", "-- schema via search_path", sql, flags=re.MULTILINE)
    # BIGINT UNSIGNED
    sql = re.sub(
        r"BIGINT\s+UNSIGNED\s+NOT\s+NULL\s+AUTO_INCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY",
        sql,
        flags=re.I,
    )
    sql = re.sub(r"BIGINT\s+UNSIGNED\s+NOT\s+NULL", "BIGINT NOT NULL", sql, flags=re.I)
    sql = re.sub(
        r"BIGINT\s+UNSIGNED\s+DEFAULT\s+NULL", "BIGINT DEFAULT NULL", sql, flags=re.I
    )
    sql = re.sub(r"BIGINT\s+UNSIGNED", "BIGINT", sql, flags=re.I)
    # INT AUTO_INCREMENT
    sql = re.sub(
        r"INT\s+NOT\s+NULL\s+AUTO_INCREMENT",
        "INT GENERATED BY DEFAULT AS IDENTITY",
        sql,
        flags=re.I,
    )
    sql = re.sub(
        r"INT\s+AUTO_INCREMENT", "INT GENERATED BY DEFAULT AS IDENTITY", sql, flags=re.I
    )
    # TINYINT
    sql = re.sub(r"TINYINT\s*\(\s*1\s*\)", "BOOLEAN", sql, flags=re.I)
    sql = re.sub(r"TINYINT\s+UNSIGNED", "SMALLINT", sql, flags=re.I)
    sql = re.sub(r"TINYINT\s*\(\s*\d+\s*\)", "SMALLINT", sql, flags=re.I)
    # DATETIME
    sql = re.sub(r"DATETIME\s*\(\s*6\s*\)", "TIMESTAMP(6)", sql, flags=re.I)
    sql = re.sub(r"\bDATETIME\b(?!\s*\()", "TIMESTAMP", sql)
    sql = re.sub(
        r"CURRENT_TIMESTAMP\s*\(\s*6\s*\)", "CURRENT_TIMESTAMP", sql, flags=re.I
    )
    sql = re.sub(r"\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP", "", sql, flags=re.I)
    # JSON -> JSONB
    sql = re.sub(r"\bJSON\b(?!\s*\()", "JSONB", sql)
    # DECIMAL
    sql = re.sub(r"DECIMAL\s*\(\s*(\d+)\s*,\s*0\s*\)", r"DECIMAL(\1)", sql, flags=re.I)
    # UNIQUE KEY -> UNIQUE, KEY -> INDEX
    sql = re.sub(r"\bUNIQUE\s+KEY\b", "UNIQUE", sql, flags=re.I)
    lines = sql.split("\n")
    out = []
    for l in lines:
        m = re.match(r"^(\s*)KEY\s+(\w+)", l)
        if m and "PRIMARY" not in l.upper():
            l = m.group(1) + "INDEX " + m.group(2) + l[m.end() :]
        out.append(l)
    sql = "\n".join(out)
    # Strip comments, ENGINE/CHARSET/COLLATE
    sql = re.sub(r",\s*COMMENT\s+\'[^\']*\'", "", sql)
    sql = re.sub(r"\s*ENGINE\s*=\s*\S+", "", sql, flags=re.I)
    sql = re.sub(r"\s*(?:DEFAULT\s+)?CHARSET\s*=\s*\S+", "", sql, flags=re.I)
    sql = re.sub(r"\s*COLLATE\s*=\s*\S+", "", sql, flags=re.I)
    sql = re.sub(r"\)\s*COMMENT\s*=\s*\'[^\']*\'(\s*;)", r")\1", sql)
    return sql


count = 0
for fname in sorted(os.listdir(SRC)):
    if not fname.endswith(".sql"):
        continue
    fp = os.path.join(SRC, fname)
    with open(fp, "r", encoding="utf-8") as f:
        c = f.read()

    if fname == "00_database.sql":
        c = """-- ============================================================================
-- 台鐵職工福利平台 — PostgreSQL 資料庫環境初始化
-- 模組：00_database.sql
-- ============================================================================
-- 手動執行：createdb -E UTF8 -T template0 tra_welfare_test
-- psql 指令：CREATE DATABASE tra_welfare_test ENCODING 'UTF8'
--   LC_COLLATE 'en_US.UTF-8' LC_CTYPE 'en_US.UTF-8';
-- 時區：ALTER DATABASE tra_welfare_test SET timezone TO 'UTC';
-- PostgreSQL 無 SQL_MODE / FOREIGN_KEY_CHECKS 概念
"""
    elif fname == "17_functions_procedures.sql":
        c = re.sub(r"^\s*DELIMITER\s+.*$", "", c, flags=re.MULTILINE)
        c = re.sub(r"\bTINYINT\b", "BOOLEAN", c, flags=re.I)
        c = re.sub(r"DECIMAL\s*\(\s*(\d+)\s*,\s*0\s*\)", r"DECIMAL(\1)", c, flags=re.I)
    elif fname == "18_triggers.sql":
        c = re.sub(r"^\s*DELIMITER\s+.*$", "", c, flags=re.MULTILINE)
    elif fname in ("19_views.sql", "20_seed_common.sql", "99_verify.sql"):
        c = re.sub(r"^\s*DELIMITER\s+.*$", "", c, flags=re.MULTILINE)
        c = convert_ddl(c)
    else:
        c = convert_ddl(c)

    with open(os.path.join(DST, fname), "w", encoding="utf-8") as f:
        f.write(c.rstrip() + "\n")
    count += 1
    print(f"  [{count:02d}] {fname}")

print(f"\nDone. {count} files written to postgresql/modules/")
